// Executed only by the native --verify runner against its isolated fixture window.
(async()=>{const checks=[];window.__chatUiResult=checks;window.__chatUiDone=false;const pause=()=>new Promise(r=>setTimeout(r,60));const check=(v,label)=>checks.push({pass:!!v,label});
 const post=chrome.webview.postMessage.bind(chrome.webview);window.__chatPosts=[];chrome.webview.postMessage=m=>{window.__chatPosts.push(m);post(m)};
 const go=async()=>{document.querySelector('[data-page=friends]').click();await pause();document.querySelector('[data-page=chat]').click();await pause();window.__chatPosts=[];};
 const set=(node,value)=>{const setter=Object.getOwnPropertyDescriptor(node.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set;setter.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));};
 const key=(node,init={})=>node.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,bubbles:true,cancelable:true,...init}));
 await go();check(document.querySelector('[data-page=chat] .unread-badge')?.textContent==='3','sidebar unread badge');check(document.querySelectorAll('.conversation-row').length===2,'direct and group list');
 const photoButton=document.querySelector('.chat-image-button');check(!!photoButton,'received image thumbnail');photoButton.click();await pause();check(!!document.querySelector('.chat-image-lightbox img'),'image expanded preview');document.querySelector('.chat-image-lightbox button').click();await pause();check(!document.querySelector('.chat-image-lightbox'),'expanded preview closes');
 let input=document.querySelector('#messenger-input');set(input,'원신 ㄱㄱ?');await pause();key(input);key(input);await pause();check(window.__chatPosts.filter(m=>m.type==='chat.send').length===1&&window.__chatPosts.find(m=>m.type==='chat.send').body==='원신 ㄱㄱ?','Enter sends once, repeated Enter deduplicated');
 await go();input=document.querySelector('#messenger-input');set(input,' \n ');await pause();key(input);check(!window.__chatPosts.some(m=>m.type==='chat.send'),'whitespace blocked');
 set(input,'한글 조합');await pause();key(input,{isComposing:true,keyCode:229});check(!window.__chatPosts.some(m=>m.type==='chat.send'),'IME composing Enter does not send');
 input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:'합'}));key(input);check(!window.__chatPosts.some(m=>m.type==='chat.send'),'composition state guard');input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'합'}));
 const shifted=key(input,{shiftKey:true});check(shifted&&!window.__chatPosts.some(m=>m.type==='chat.send'),'Shift+Enter leaves newline default intact');set(input,'첫 줄\n다음 줄');await pause();key(input);await pause();check(window.__chatPosts.find(m=>m.type==='chat.send')?.body==='첫 줄\n다음 줄','multiline message preserved');
 await go();document.querySelector('.older-messages').click();check(window.__chatPosts.some(m=>m.type==='chat.older'),'older history requested');
 document.querySelector('[data-page=friends]').click();await pause();window.__chatPosts=[];[...document.querySelectorAll('.friend-card-line button')].find(b=>b.textContent==='메시지').click();check(window.__chatPosts.some(m=>m.type==='chat.direct'&&m.user==='game'),'friend message opens target direct');
 [...document.querySelectorAll('button')].find(b=>b.textContent==='프로필 이미지 변경').click();await pause();check(!!document.querySelector('[role=dialog]'),'avatar editor opened');
 const canvas=document.createElement('canvas');canvas.width=400;canvas.height=300;const ctx=canvas.getContext('2d');ctx.fillStyle='#e080a0';ctx.fillRect(0,0,400,300);ctx.fillStyle='#3060d0';ctx.fillRect(0,0,150,300);
 const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const files=new DataTransfer();files.items.add(new File([blob],'test.png',{type:'image/png'}));const file=document.querySelector('input[type=file]');file.files=files.files;file.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,200));
 const ranges=document.querySelectorAll('.chat-modal input[type=range]');set(ranges[0],'1.8');set(ranges[1],'.7');await pause();check(document.querySelector('.avatar-crop-area canvas').width===224,'avatar crop canvas and zoom');
 [...document.querySelectorAll('.chat-modal button')].find(b=>b.textContent==='이미지 저장').click();await pause();const upload=window.__chatPosts.find(m=>m.type==='chat.avatar');check(upload?.image.startsWith('data:image/jpeg;base64,')&&upload.image.length<180000,'avatar optimized JPEG submitted only on save');
 const im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject;im.src=upload.image;});check(im.width===256&&im.height===256,'avatar output 256 square');
 await go();[...document.querySelectorAll('button')].find(b=>b.textContent==='새 그룹').click();await pause();check(!!document.querySelector('[aria-label="새 그룹 만들기"]'),'group creation dialog');set(document.querySelector('.chat-modal input:not([type=checkbox])'),'테스트 게임팟');document.querySelector('.group-pick input').click();await pause();window.__chatPosts=[];[...document.querySelectorAll('.chat-modal button')].find(b=>b.textContent==='그룹 만들기').click();await pause();const group=window.__chatPosts.find(m=>m.type==='chat.group');check(group?.name==='테스트 게임팟'&&group.users.length===1,'group creation selected friends only');
 await go();let attachmentFile=document.querySelector('.chat-compose input[type=file]');attachmentFile.files=files.files;attachmentFile.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,250));check(!!document.querySelector('.chat-attachment-preview img'),'image attachment local preview');check(!window.__chatPosts.some(m=>m.type==='chat.image'),'preview does not upload');input=document.querySelector('#messenger-input');key(input);key(input);await pause();const imageSend=window.__chatPosts.filter(m=>m.type==='chat.image');check(imageSend.length===1&&imageSend[0].data.startsWith('data:image/jpeg;base64,'),'image only Enter send and deduplication');
 await go();const pasted=new DataTransfer();pasted.items.add(new File([blob],'clipboard.png',{type:'image/png'}));input=document.querySelector('#messenger-input');input.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:pasted}));await new Promise(r=>setTimeout(r,250));check(!!document.querySelector('.chat-attachment-preview img'),'clipboard image preview');document.querySelector('.chat-attachment-preview button').click();await pause();check(!document.querySelector('.chat-attachment-preview'),'remove attachment before send');
 const invalid=new DataTransfer();invalid.items.add(new File(['no'],'invalid.svg',{type:'image/svg+xml'}));attachmentFile=document.querySelector('.chat-compose input[type=file]');attachmentFile.files=invalid.files;attachmentFile.dispatchEvent(new Event('change',{bubbles:true}));await pause();check(!!document.querySelector('[role=alert]')&&!document.querySelector('.chat-attachment-preview'),'unsupported image rejected');
 window.__chatUiResult=checks;})().catch(e=>window.__chatUiResult.push({pass:false,label:e.stack})).finally(()=>window.__chatUiDone=true);

