using System;using System.Collections;using System.Collections.Generic;using System.Globalization;using System.Linq;using System.Net.Http;using System.Text.RegularExpressions;using System.Threading;using System.Threading.Tasks;using System.Web.Script.Serialization;

// Public profile document only. Decode embedded Remix loader JSON as DATA, never
// execute scripts or scrape protected APIs. No fallback provider, login, or challenge solver.
internal sealed class EternalHippyProvider:IEternalReturnDataProvider {
 readonly HttpClient http;readonly JavaScriptSerializer json=new JavaScriptSerializer{MaxJsonLength=8*1024*1024,RecursionLimit=100};
 internal EternalHippyProvider(string root,HttpMessageHandler handler=null){http=new HttpClient(new ProviderHttpPolicy("hippy",root,handler)){Timeout=TimeSpan.FromSeconds(20),MaxResponseContentBufferSize=8*1024*1024};http.DefaultRequestHeaders.UserAgent.ParseAdd("NyangGaming/0.1");}
 internal static string Normalize(string input){string name=(input??"").Trim();if(name.StartsWith("https://",StringComparison.OrdinalIgnoreCase)){Uri uri;if(!Uri.TryCreate(name,UriKind.Absolute,out uri)||uri.Host!="hippygg.com"||!uri.IsDefaultPort||uri.UserInfo!="")throw BadInput();var match=Regex.Match(uri.AbsolutePath,@"^/user/([^/]+)/?$");if(!match.Success)throw BadInput();name=Uri.UnescapeDataString(match.Groups[1].Value);}if(name.Length<1||name.Length>80||name.Any(char.IsControl)||name.IndexOfAny(new[]{'/','\\','?','#'})>=0||name.Contains("://"))throw BadInput();return name;}
 static ErFailure BadInput(){return new ErFailure("input","닉네임 또는 히피지지 전적 주소를 입력해 주세요.");}
 static ErFailure Format(){return new ErFailure("format","히피지지 데이터 조회 실패 · 페이지 구조가 변경됐거나 통계가 불완전해요. 마지막 정상 기록을 유지해요.",900);}
 public async Task<ErData> Read(string key,string nickname,CancellationToken token){nickname=Normalize(nickname);using(var response=await http.GetAsync("https://hippygg.com/user/"+Uri.EscapeDataString(nickname),token)){int status=(int)response.StatusCode;
  if(status==401||status==403)throw new ErFailure("siteBlocked","데이터 조회 실패 · 히피지지의 접근 제한으로 이 Provider 조회를 중단했어요.",900);
  if(status==429)throw new ErFailure("rateLimit","히피지지 요청 제한으로 대기 중이에요.",LeagueIplolProvider.RetryAfter(response));
  if(status==404)throw new ErFailure("notFound","히피지지에서 이 닉네임의 기록을 찾지 못했어요.",900);
  if(!response.IsSuccessStatusCode)throw new ErFailure("service","히피지지 데이터 조회 실패 · 이전 정상 기록을 유지해요.",900);
  var data=Parse(nickname,await response.Content.ReadAsStringAsync());data.updatedAt=ProviderHttpPolicy.Fetched(response);return data;
 }}
 internal static ErData Parse(string nickname,string html){try{
  var serializer=new JavaScriptSerializer{MaxJsonLength=8*1024*1024,RecursionLimit=100};var match=Regex.Match(html,@"streamController\.enqueue\((""(?:\\.|[^""\\])*"")\)",RegexOptions.None,TimeSpan.FromSeconds(2));if(!match.Success)throw Format();string payload=serializer.Deserialize<string>(match.Groups[1].Value);var flat=serializer.DeserializeObject(payload) as object[];if(flat==null||flat.Length>100000)throw Format();int budget=200000;var decoded=Decode(flat,0,0,new HashSet<int>(),ref budget);var data=ErJson.Get(ErJson.Get(decoded,"loaderData"),"routes/user.$nickname");
  if(!string.IsNullOrEmpty(ErJson.Text(data,"error")))throw new ErFailure("notFound","히피지지에서 이 계정의 시즌 기록을 제공하지 못했어요.",900);
  var user=ErJson.Get(data,"user");var stats=ErJson.Get(data,"userStats");int? season=ErJson.Int(stats,"seasonId"),games=ErJson.Int(stats,"totalGames"),wins=ErJson.Int(stats,"totalWins"),rp=ErJson.Int(stats,"mmr");
  if(!string.Equals(ErJson.Text(user,"nickname"),nickname,StringComparison.OrdinalIgnoreCase)||!season.HasValue||season<=0||ErJson.Int(data,"selectedSeasonId")!=season||!games.HasValue||games<0||!wins.HasValue||wins<0||wins>games||!rp.HasValue||rp<0||ErJson.Int(stats,"matchingMode")!=3||ErJson.Int(stats,"matchingTeamMode")!=3)throw Format();
  var tiers=new Dictionary<string,string>{{"diamond","다이아몬드"},{"platinum","플래티넘"},{"gold","골드"},{"gold_minus","골드 미만"},{"meteorite","메테오라이트"},{"mithril","미스릴"},{"demigod","데미갓"},{"eternity","이터니티"}};string tier;if(!tiers.TryGetValue(ErJson.Text(data,"userTier"),out tier))tier=ErJson.Text(data,"userTier");
  string label="시즌 ID "+season;var s=ErJson.Rows(ErJson.Get(data,"seasons")).FirstOrDefault(x=>ErJson.Int(x,"seasonID")==season);var number=Regex.Match(ErJson.Text(s,"seasonName"),@"^Season([0-9]+)$");int n;if(number.Success&&int.TryParse(number.Groups[1].Value,out n)&&n>9)label="시즌 "+(n-9); // same display conversion as the site's public client
  var result=new ErData{source="hippy",sourceUrl="https://hippygg.com/user/"+Uri.EscapeDataString(nickname),nickname=nickname,seasonId=season,seasonName=label,rp=rp,ranking=ErJson.Int(stats,"rank"),seasonGames=games,seasonWins=wins,tier=tier,updatedAt=DateTime.UtcNow.ToString("o"),rankMessage="출처: 히피지지 · 시즌 스쿼드 랭크 통계",metadataMessage="원본 데이터 갱신 시각 미제공 · 개별 경기 기록과 경기별 RP 변화는 제공하지 않아요.",seasonAverageRank=Number(stats,"averageRank"),seasonAverageKills=Number(stats,"averageKills"),seasonAverageAssists=Number(stats,"averageAssistants")};
  foreach(var c in ErJson.Rows(ErJson.Get(stats,"characterStats"))){int? code=ErJson.Int(c,"characterCode"),count=ErJson.Int(c,"totalGames"),won=ErJson.Int(c,"wins");if(!code.HasValue||!count.HasValue||count<0||!won.HasValue||won<0||won>count)throw Format();result.seasonCharacters.Add(new ErSeasonCharacter{name=EternalCraftProvider.CharacterName(code,""),games=count.Value,wins=won.Value,averageRank=Number(c,"averageRank")});}return result;
 }catch(ErFailure){throw;}catch{throw Format();}}
 static double? Number(object value,string field){double n;return double.TryParse(ErJson.Text(value,field),NumberStyles.Float,CultureInfo.InvariantCulture,out n)&&!double.IsNaN(n)&&!double.IsInfinity(n)?(double?)n:null;}
 static object Decode(object[] flat,int index,int depth,HashSet<int> active,ref int budget){if(index<0)return null;if(index>=flat.Length||depth>64||--budget<0||!active.Add(index))throw Format();try{object value=flat[index];var map=value as Dictionary<string,object>;if(map!=null){var output=new Dictionary<string,object>();foreach(var pair in map){int key;if(!pair.Key.StartsWith("_")||!int.TryParse(pair.Key.Substring(1),out key)||key<0||key>=flat.Length||!(flat[key] is string))throw Format();output[(string)flat[key]]=Decode(flat,Convert.ToInt32(pair.Value),depth+1,active,ref budget);}return output;}var array=value as object[];if(array!=null){var output=new List<object>();foreach(var item in array){if(!(item is int))throw Format();output.Add(Decode(flat,(int)item,depth+1,active,ref budget));}return output.ToArray();}return value;}finally{active.Remove(index);}}
 public void Dispose(){http.Dispose();}
}
