using System;using System.Collections.Generic;using System.Linq;using System.IO;using System.Threading.Tasks;using System.Web.Script.Serialization;
internal static class MessengerTests {
 static async Task<bool> Until(Func<bool> test,int timeout=12000){var start=DateTime.UtcNow;while((DateTime.UtcNow-start).TotalMilliseconds<timeout){if(test())return true;await Task.Delay(100);}return false;}
 internal static async Task Live(string output){var lines=new List<string>();Action<bool,string> check=(ok,label)=>{lines.Add((ok?"PASS ":"FAIL ")+label);File.WriteAllLines(output,lines);if(!ok)throw new Exception(label);};
  string folder=Path.Combine(Path.GetDirectoryName(output),"messenger-host-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);string ar=Path.Combine(folder,"a"),br=Path.Combine(folder,"b");Directory.CreateDirectory(ar);Directory.CreateDirectory(br);
  using(var a=new FriendsService(ar,false))using(var b=new FriendsService(br,false)){
   string route=Guid.NewGuid().ToString();check(ChatNotifications.Parse(ChatNotifications.Link(route))==route&&ChatNotifications.Parse("https://example.com/"+route)==null&&ChatNotifications.Parse("nyang-gaming-chat://room/not-a-room")==null,"notification routes accept room UUID only");
   await a.Profile("메신저호스트A");await b.Profile("메신저호스트B");check(a.View.connected&&b.View.connected,"native auth profiles");string aid=a.ChatUser,bid=b.ChatUser;
   await a.Action("request",ErJson.Text(b.View.me,"code"),false);await b.Action("respond",aid,true);await a.Action("refresh",null,false);
   await a.Chat.Direct(bid);await b.Chat.Direct(aid);check(a.Chat.View.room!=null&&a.Chat.View.room==b.Chat.View.room,"direct navigation selects same room");string room=a.Chat.View.room;
   int notifications=0;b.Chat.Notification+=(r,t,body)=>notifications++;
   await a.Chat.Tick(false);await b.Chat.Tick(false);check(await Until(()=>a.Chat.View.connected&&b.Chat.View.connected),"native WebSockets joined");await Task.Delay(1200);
   string id=Guid.NewGuid().ToString();await a.Chat.SendMessage(room,"한글 실시간 메시지\n두 번째 줄",id);check(await Until(()=>b.Chat.View.messages.Any(m=>ErJson.Text(m,"id")==id)),"message arrives without polling");check(notifications==1,"background message notification event");
   await a.Chat.SendMessage(room,"한글 실시간 메시지\n두 번째 줄",id);await Task.Delay(400);check(b.Chat.View.messages.Length==1&&notifications==1,"retry and notification deduplication");
   b.Chat.Settings(false);id=Guid.NewGuid().ToString();await a.Chat.SendMessage(room,"전체 알림 끈 메시지",id);check(await Until(()=>b.Chat.View.messages.Length==2)&&notifications==1&&b.Chat.View.unread==2,"global mute preserves reception and unread");
   b.Chat.Settings(true);await b.Chat.Manage(room,"notify",null,null,false);await a.Chat.SendMessage(room,"방 알림 끈 메시지",Guid.NewGuid().ToString());check(await Until(()=>b.Chat.View.messages.Length==3)&&notifications==1,"room mute suppresses notification");
   await b.Chat.Manage(room,"notify",null,null,true);await b.Chat.Tick(true);await a.Chat.SendMessage(room,"열린 방 메시지",Guid.NewGuid().ToString());check(await Until(()=>b.Chat.View.messages.Length==4)&&notifications==1,"foreground current room suppresses notification");
   await b.Chat.Read(room,b.Chat.View.messages.Max(m=>ErJson.Long(m,"seq")));check(await Until(()=>b.Chat.View.unread==0),"read state clears unread via realtime");
   b.Chat.DisconnectForTest();await a.Chat.SendMessage(room,"재연결 검증",Guid.NewGuid().ToString());check(await Until(()=>b.Chat.View.connected&&b.Chat.View.messages.Length==5,20000),"native reconnect reconciles missed message");
   string imagePath=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"..","messenger-test-avatar.jpg");await a.Chat.Avatar("data:image/jpeg;base64,"+Convert.ToBase64String(File.ReadAllBytes(imagePath)),null);check(a.Chat.View.uploadState.Contains("저장했어요"),"native optimized upload");check(await Until(()=>b.Chat.View.avatars.Count>0),"native signed avatar refresh");
   string photo=Guid.NewGuid().ToString(),photoData="data:image/jpeg;base64,"+Convert.ToBase64String(File.ReadAllBytes(imagePath));await a.Chat.SendImage(room,"사진 테스트",photo,photoData);check(a.Chat.View.sentId==photo,"native photo upload and message commit");check(await Until(()=>b.Chat.View.messages.Any(m=>ErJson.Text(m,"id")==photo)&&b.Chat.View.images.Count>0),"recipient receives photo and signed URL via realtime");
   await a.Chat.SendImage(room,"사진 테스트",photo,photoData);check(a.Chat.View.sentId==photo&&a.Chat.View.messages.Count(m=>ErJson.Text(m,"id")==photo)==1,"duplicate upload retry stays idempotent");
   using(var fetch=new System.Net.Http.HttpClient()){var bytes=await fetch.GetByteArrayAsync(b.Chat.View.images.Values.First());check(bytes.SequenceEqual(File.ReadAllBytes(imagePath)),"recipient downloads exact optimized JPEG");}
   string invalid=Guid.NewGuid().ToString();await a.Chat.SendImage(room,"",invalid,"data:image/svg+xml;base64,PHN2Zz4=");check(a.Chat.View.failedId==invalid&&a.Chat.View.sentId!=invalid,"native rejects non-JPEG attachment");
   string group=Guid.NewGuid().ToString();await a.Chat.Group("사진 그룹",new[]{bid},group);await b.Chat.Open(group);string groupPhoto=Guid.NewGuid().ToString();await a.Chat.SendImage(group,"",groupPhoto,photoData);check(await Until(()=>b.Chat.View.images.Count>0&&b.Chat.View.messages.Any(m=>ErJson.Text(m,"id")==groupPhoto)),"group photo received");await b.Chat.Manage(group,"leave",null,null,null);check(b.Chat.View.room==null,"group leave revokes selected photo history");await a.Chat.Manage(group,"leave",null,null,null);await a.Chat.Open(room);await b.Chat.Open(room);
   await a.Action("remove",bid,false);await b.Chat.Refresh();check(b.Chat.View.room==null,"removed friendship clears selected direct");
   string failed=Guid.NewGuid().ToString();await a.Chat.SendMessage(room,"실패 후 재전송 검증",failed);check(a.Chat.View.failedId==failed&&a.Chat.View.sentId!=failed,"failed send not acknowledged");
   await a.Action("request",ErJson.Text(b.View.me,"code"),false);await b.Action("respond",aid,true);await a.Chat.SendMessage(room,"실패 후 재전송 검증",failed);await b.Chat.Open(room);await Task.Delay(300);await b.Chat.Tick(false);check(a.Chat.View.sentId==failed&&b.Chat.View.messages.Count(m=>ErJson.Text(m,"id")==failed)==1,"same nonce succeeds after retry");
   await a.Action("remove",bid,false);check(File.Exists(Path.Combine(br,"chat-settings.json")),"notification preference persisted");
  }
 }
 internal static async Task RetryCheck(string folder,string output){var lines=new List<string>();using(var a=new FriendsService(Path.Combine(folder,"a"),false))using(var b=new FriendsService(Path.Combine(folder,"b"),false)){await a.Action("refresh",null,false);await b.Action("refresh",null,false);string room=Convert.ToString(await a.ChatRpc("nyang_chat_direct",new{p_user=b.ChatUser}));var page=ErJson.Rows(await a.ChatRpc("nyang_chat_page",new{p_room=room,p_before=(long?)null}));var message=page.LastOrDefault(m=>ErJson.Text(m,"body")=="실패 후 재전송 검증");if(message==null)throw new Exception("Expected retry message missing");string id=ErJson.Text(message,"id");await a.Chat.SendMessage(room,"실패 후 재전송 검증",id);await b.Chat.Open(room);await Task.Delay(400);await b.Chat.Tick(false);page=ErJson.Rows(await b.ChatRpc("nyang_chat_page",new{p_room=room,p_before=(long?)null}));lines.Add((a.Chat.View.sentId==id&&page.Count(m=>ErJson.Text(m,"id")==id)==1?"PASS ":"FAIL ")+"same nonce persists exactly once after retry");lines.Add((b.Chat.View.messages.Any(m=>ErJson.Text(m,"id")==id)?"PASS ":"FAIL ")+"reopened room displays retried message after refresh");}File.WriteAllLines(output,lines);}
 internal static async Task NotificationCheck(string output){try{string root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"KoruGaming_Next","UserData");using(var service=new FriendsService(root,false)){var state=await service.ChatRpc("nyang_chat_state",new{});var room=ErJson.Rows(ErJson.Get(state,"rooms")).FirstOrDefault();if(room==null){File.WriteAllText(output,"No existing conversation available for notification test.");return;}var history=ErJson.Rows(await service.ChatRpc("nyang_chat_page",new{p_room=ErJson.Text(room,"id"),p_before=(long?)null}));await service.Action("refresh",null,false);var latest=history.LastOrDefault(m=>ErJson.Text(m,"sender")!=service.ChatUser)??history.LastOrDefault();string sender=latest==null?"냥게이밍":ErJson.Text(ErJson.Rows(ErJson.Get(room,"members")).FirstOrDefault(m=>ErJson.Text(m,"id")==ErJson.Text(latest,"sender")),"nickname");string body=latest==null?"이 알림을 누르면 채팅방이 열려요.":ErJson.Text(latest,"body");ChatNotifications.Show(ErJson.Text(room,"id"),sender+" · 알림 미리보기",body.Length>180?body.Substring(0,180)+"…":body);File.WriteAllText(output,"PASS Windows Toast submitted for existing authorized conversation");}}catch(Exception e){File.WriteAllText(output,e.ToString());}}
 internal static void Fixture(FriendsService friends){var v=friends.Chat.View;v.connected=true;v.message="화면 검증용 채팅 · 실제 대화 아님";v.room="room-test";v.unread=3;v.hasMore=true;
  var members=new[]{new{id="self",nickname="검증용 냥냥",lastRead=2},new{id="game",nickname="게임 중인 친구",lastRead=1}};
  v.rooms=new object[]{new{id="room-test",kind="direct",name="",notifications=true,unread=2,lastSeq=2,members=members,latest=new{sender="game",body="오늘 같이 게임할까?",sent_at=DateTime.UtcNow.ToString("o")}},new{id="group-test",kind="group",name="금요일 게임팟",notifications=false,unread=1,lastSeq=1,members=members,latest=new{sender="game",body="10분 뒤에 만나요",sent_at=DateTime.UtcNow.ToString("o")}}};
  string fixtureImage=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"..","messenger-test-avatar.jpg");if(File.Exists(fixtureImage))v.images["fixture/photo.jpg"]="data:image/jpeg;base64,"+Convert.ToBase64String(File.ReadAllBytes(fixtureImage));
  v.profiles=members.Cast<object>().ToArray();v.messages=new object[]{new{id="one",seq=1,sender="game",body="오늘 같이 게임할까? 🐾",sent_at=DateTime.UtcNow.ToString("o")},new{id="two",seq=2,sender="self",body="응! 잠시 후에 만나자\nShift+Enter 줄바꿈 확인",sent_at=DateTime.UtcNow.ToString("o")},new{id="photo",seq=3,sender="game",body="[사진]",image_path="fixture/photo.jpg",image_width=256,image_height=256,sent_at=DateTime.UtcNow.ToString("o")}};
 }
}

