using System;using System.IO;using System.Linq;using System.Net;using System.Net.Http;using System.Threading;using System.Threading.Tasks;using System.Collections.Generic;using System.Text;using System.Web.Script.Serialization;
internal static class ProviderPolicyTests {
 sealed class Fake:HttpMessageHandler {internal int calls;internal Func<HttpRequestMessage,HttpResponseMessage> reply=q=>Reply(200,"{}");protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage q,CancellationToken t){Interlocked.Increment(ref calls);return Task.FromResult(reply(q));}}
 static HttpResponseMessage Reply(int code,string body,string type="application/json"){return new HttpResponseMessage((HttpStatusCode)code){Content=new StringContent(body,Encoding.UTF8,type)};}
 static void Check(bool value,string name,List<string> log){if(!value)throw new Exception(name);log.Add("PASS "+name);}
 internal static async Task Run(string fixture,string output){var log=new List<string>();string root=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(output)),"policy-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{
 DateTime now=DateTime.UtcNow;var fake=new Fake();var policy=new ProviderHttpPolicy("cache",root,fake){Clock=()=>now};using(var c=new HttpClient(policy)){
 var a=await c.GetAsync("https://example.test/player/a");string stamp=ProviderHttpPolicy.Fetched(a);await Task.WhenAll(Enumerable.Range(0,8).Select(x=>c.GetAsync("https://example.test/player/a")));Check(fake.calls==1,"concurrent same request cached",log);
 now=now.AddMinutes(14);a=await c.GetAsync("https://example.test/player/a");Check(fake.calls==1&&Math.Abs((DateTime.Parse(stamp)-DateTime.Parse(ProviderHttpPolicy.Fetched(a))).TotalMilliseconds)<1,"cache timestamp and 15 minute floor",log);
 await c.GetAsync("https://example.test/player/b");await c.PostAsync("https://example.test/player/a",new StringContent("one"));await c.PostAsync("https://example.test/player/a",new StringContent("two"));Check(fake.calls==4,"accounts and request bodies isolated",log);
 now=now.AddMinutes(1);await c.GetAsync("https://example.test/player/a");Check(fake.calls==5,"expiry permits single network refresh",log);}
 var restart=new Fake();using(var c=new HttpClient(new ProviderHttpPolicy("cache",root,restart){Clock=()=>now})){await c.GetAsync("https://example.test/player/a");Check(restart.calls==0,"cache persists across handler restart",log);}
 var rate=new Fake{reply=q=>Reply(429,"{}")};using(var c=new HttpClient(new ProviderHttpPolicy("rate",root,rate){Clock=()=>now})){
 var r=await c.GetAsync("https://example.test/a");Check(r.Headers.RetryAfter.Delta==TimeSpan.FromMinutes(15),"429 initial exponential delay",log);await c.GetAsync("https://example.test/b");Check(rate.calls==1,"429 pauses whole provider",log);
 now=now.AddMinutes(15);r=await c.GetAsync("https://example.test/a");Check(rate.calls==2&&r.Headers.RetryAfter.Delta==TimeSpan.FromMinutes(30),"429 second exponential delay",log);
 now=now.AddMinutes(30);rate.reply=q=>Reply(200,"{}");await c.GetAsync("https://example.test/a");now=now.AddMinutes(15);rate.reply=q=>Reply(429,"{}");r=await c.GetAsync("https://example.test/a");Check(r.Headers.RetryAfter.Delta==TimeSpan.FromMinutes(15),"success resets rate strikes",log);}
 foreach(bool date in new[]{false,true}){var h=new Fake{reply=q=>{var r=Reply(429,"{}");r.Headers.RetryAfter=date?new System.Net.Http.Headers.RetryConditionHeaderValue(new DateTimeOffset(now.AddHours(2))):new System.Net.Http.Headers.RetryConditionHeaderValue(TimeSpan.FromHours(2));return r;}};using(var c=new HttpClient(new ProviderHttpPolicy(date?"date":"delta",root,h){Clock=()=>now})){var r=await c.GetAsync("https://example.test/a");Check(Math.Abs(r.Headers.RetryAfter.Delta.Value.TotalSeconds-7200)<2,"Retry-After "+(date?"date":"delta"),log);now=now.AddHours(1);await c.GetAsync("https://example.test/b");Check(h.calls==1,"no early retry "+date,log);}}
 int i=0;foreach(var make in new Func<HttpResponseMessage>[]{()=>Reply(200,"{\"code\":403}"),()=>Reply(401,"{}"),()=>Reply(403,"{}"),()=>Reply(200,"<html>/cdn-cgi/challenge-platform/</html>","text/html"),()=>Reply(200,"{\"profile\":{\"isPrivate\":true}}"),()=>{var r=Reply(302,"");r.Headers.Location=new Uri("https://example.test/login");return r;},()=>Reply(200,"{\"retcode\":1034}"),()=>{var r=Reply(200,"");r.Headers.Add("cf-mitigated","challenge");return r;}}){string name="blocked"+(i++);var h=new Fake{reply=q=>make()};using(var c=new HttpClient(new ProviderHttpPolicy(name,root,h){Clock=()=>now})){var r=await c.GetAsync("https://example.test/a");Check((int)r.StatusCode==403,"block detected "+name,log);now=now.AddDays(1);await c.GetAsync("https://example.test/b");Check(h.calls==1,"no alternate endpoint after block "+name,log);}var h2=new Fake();using(var c=new HttpClient(new ProviderHttpPolicy(name,root,h2){Clock=()=>now})){await c.GetAsync("https://example.test/a");Check(h2.calls==0,"block survives restart "+name,log);}}
 var independent=new Fake();using(var c=new HttpClient(new ProviderHttpPolicy("independent",root,independent){Clock=()=>now})){Check((await c.GetAsync("https://example.test/a")).IsSuccessStatusCode&&independent.calls==1,"other providers unaffected",log);}
 var network=new Fake{reply=q=>{throw new HttpRequestException();}};using(var c=new HttpClient(new ProviderHttpPolicy("network",root,network){Clock=()=>now})){await c.GetAsync("https://example.test/a");await c.GetAsync("https://example.test/a");Check(network.calls==1,"failed requests also obey 15 minute floor",log);}
 var html=File.ReadAllText(fixture);var data=EternalHippyProvider.Parse("냥냥",html);Check(data.source=="hippy"&&data.rp>0&&data.seasonGames>0&&data.seasonCharacters.Count>0&&data.matches.Count==0,"Hippy real fixture season-only parsing",log);Check(data.seasonCharacters.All(x=>!x.name.StartsWith("실험체 #")),"Hippy character names resolved",log);
 bool bad=false;try{EternalHippyProvider.Parse("냥냥","<html>changed</html>");}catch(ErFailure e){bad=e.State=="format";}Check(bad,"Hippy structure change fails independently",log);
 var hp=new Fake{reply=q=>Reply(200,html,"text/html")};using(var provider=new EternalHippyProvider(root,hp)){await provider.Read(null,"냥냥",CancellationToken.None);await provider.Read(null,"냥냥",CancellationToken.None);Check(hp.calls==1,"Hippy full provider uses cache",log);}
 log.Add("ALL PASS: "+log.Count);File.WriteAllLines(output,log,Encoding.UTF8);
 }catch(Exception e){log.Add("FAIL "+e);File.WriteAllLines(output,log,Encoding.UTF8);throw;}}
 internal static async Task Live(string name,string output){try{using(var p=new EternalHippyProvider(ProviderHttpPolicy.DefaultRoot)){var d=await p.Read(null,name,CancellationToken.None);File.WriteAllText(output,new JavaScriptSerializer().Serialize(d),Encoding.UTF8);}}catch(Exception e){File.WriteAllText(output,e.ToString(),Encoding.UTF8);}}
}
