import React,{useEffect,useRef,useState} from 'react';
import {Activity,CalendarDays,Clock3,Gamepad2,X} from 'lucide-react';
import {send,duration} from './bridge';
import './activity.css';
import {Avatar} from './ChatProfile';
const games={genshin:{name:'원신',genre:'RPG'},eternal:{name:'이터널 리턴',genre:'전략 / 배틀로얄'},league:{name:'League of Legends',genre:'MOBA'},valorant:{name:'VALORANT',genre:'FPS'}};
const periods=[['today','오늘'],['7','최근 7일'],['30','최근 30일'],['month','이번 달'],['year','올해'],['all','전체']];
export const kstToday=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);
export const historyQuery=user=>({user,year:Number(kstToday().slice(0,4)),period:'30',game:'',day:kstToday()});
const gameName=id=>games[id]?.name||id;
const time=n=>n>0&&n<60?'1분 미만':duration(n);
const level=n=>n<=0?0:n<3600?1:n<10800?2:n<21600?3:4;
function daysBetween(start,end){let a=[];for(let d=new Date(start+'T00:00:00Z');d<=new Date(end+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1))a.push(d.toISOString().slice(0,10));return a;}
function RangeBars({rows,total}){return <div className="activity-bars">{rows.map((r,i)=><div className="activity-bar-row" key={r.id}><div><span>{r.name}</span><strong>{time(r.seconds)} <small>{total?Math.round(r.seconds/total*100):0}%</small></strong></div><div className="activity-bar-track"><i style={{width:`${total?Math.min(100,r.seconds/total*100):0}%`}}/></div></div>)}</div>}
function Trend({history,period,today}){
 let start=period==='today'?today:period==='month'?today.slice(0,7)+'-01':period==='year'?today.slice(0,4)+'-01-01':period==='all'?history.firstDate||today:new Date(new Date(today+'T00:00:00Z').getTime()-(period==='7'?6:29)*86400000).toISOString().slice(0,10);
 const byDay=Object.fromEntries((history.trend||[]).map(d=>[d.day,d.seconds]));let dates=daysBetween(start,today);const monthly=dates.length>93;let rows=[];
 if(monthly){let months={};dates.forEach(d=>months[d.slice(0,7)]=(months[d.slice(0,7)]||0)+(byDay[d]||0));rows=Object.entries(months).map(([day,seconds])=>({day,seconds}));}else rows=dates.map(day=>({day,seconds:byDay[day]||0}));
 const max=Math.max(1,...rows.map(r=>r.seconds));return <><div className="between"><h3><Activity size={18}/> 플레이 추이</h3><span className="small muted">{monthly?'월별 합계':'날짜별 합계'} · {start} ~ {today}</span></div><div className="activity-trend-scroll" tabIndex={0} aria-label="플레이시간 추이 그래프"><div className="activity-trend" style={{minWidth:rows.length*23}}>{rows.map((r,i)=><div className="activity-trend-column" key={r.day} title={`${r.day} · ${time(r.seconds)}`}><div className="activity-trend-slot"><i style={{height:r.seconds?`${Math.max(2,r.seconds/max*100)}%`:'2px',opacity:r.seconds?1:.25}}/></div><span>{monthly?r.day.slice(2):rows.length<=7?r.day.slice(5):i%7===0?r.day.slice(5):'·'}</span></div>)}</div></div><p className="small muted">막대에 마우스를 올리면 날짜와 플레이시간을 볼 수 있어요. 기록이 없는 날은 0분입니다.</p></>;
}
export function ActivityDashboard({view,profile,status,chat={}}){
 const [query,setQuery]=useState(()=>historyQuery(profile.id));const today=kstToday();const history=view.history;const own=profile.id===view.me?.id;
 const panel=useRef(null);useEffect(()=>{send('friends.history',historyQuery(profile.id));panel.current?.scrollIntoView({block:'start'});},[profile.id]);
 const update=patch=>{const next={...query,...patch};setQuery(next);send('friends.history',next);};
 const calendar=Object.fromEntries((history?.calendar||[]).map(d=>[d.day,d.seconds]));const dates=daysBetween(`${query.year}-01-01`,`${query.year}-12-31`);const padding=new Date(`${query.year}-01-01T00:00:00Z`).getUTCDay();
 const summary=history?.summary||{};const rankings=history?.games||[];const genres={};rankings.forEach(g=>{const genre=games[g.gameId]?.genre||'기타';genres[genre]=(genres[genre]||0)+g.seconds;});
 const sessionTime=t=>new Date(t).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});
 return <section ref={panel} className="card activity-dashboard"><div className="between activity-profile"><div className="friend-profile-avatar"><Avatar person={profile} chat={chat} size={52}/><div><span className="eyebrow">PLAY HISTORY</span><h2>{own?'내 플레이 기록':`${profile.nickname}의 플레이 기록`}</h2>{status}</div></div><div className="chat-actions">{!own&&<button className="button secondary" onClick={()=>send('chat.direct',{user:profile.id})}>메시지</button>}<button className="button secondary" aria-label="기록 닫기" onClick={()=>send('friends.history.close')}><X size={17}/></button></div></div>
 <p className="small muted" role="status">{view.historyMessage}</p>
 {own&&<p className="activity-sharing">{view.options?.shareHistory?'승인한 친구에게 기록 공개 중':'내 기록은 비공개예요'}{view.historyPending?' · 서버 반영 대기':''} · 공유 설정은 아래에서 변경할 수 있어요.</p>}
 <div className="activity-filters"><label>기간<select value={query.period} onChange={e=>update({period:e.target.value})}>{periods.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>게임<select value={query.game} onChange={e=>update({game:e.target.value})}><option value="">모든 게임</option>{Object.entries(games).map(([id,g])=><option key={id} value={id}>{g.name}</option>)}</select></label><button className="button secondary" disabled={view.busy} onClick={()=>send('friends.history',query)}>새로고침</button></div>
 {history?.allowed?<><div className="between"><h3><CalendarDays size={18}/> 플레이 달력</h3><label className="activity-year">연도<select value={query.year} onChange={e=>update({year:Number(e.target.value),period:'all',day:`${e.target.value}-01-01`})}>{Array.from({length:Math.max(2,Number(today.slice(0,4))-Number((history.firstDate||today).slice(0,4))+1)},(_,i)=>Number(today.slice(0,4))-i).map(y=><option key={y}>{y}</option>)}</select></label></div>
 <div className="activity-calendar-scroll" tabIndex={0} aria-label={`${query.year}년 플레이 달력`}><div className="activity-months">{Array.from({length:12},(_,i)=><span key={i} style={{gridColumn:Math.floor((padding+dates.indexOf(`${query.year}-${String(i+1).padStart(2,'0')}-01`))/7)+1}}>{i+1}월</span>)}</div><div className="activity-calendar">{Array.from({length:padding},(_,i)=><span key={'pad'+i}/>)}{dates.map(day=><button key={day} className={`activity-day heat-${level(calendar[day]||0)} ${query.day===day?'chosen':''}`} disabled={day>today} aria-label={`${day} ${time(calendar[day]||0)}`} aria-pressed={query.day===day} title={`${day} · ${time(calendar[day]||0)}`} onClick={()=>update({day})}/>)}</div></div>
 <div className="activity-legend"><span>선택 기간 내 기록 · 일요일부터 세로 순서</span><span>적음 {[0,1,2,3,4].map(n=><i className={'heat-'+n} key={n}/>)} 많음</span></div>
 <div className="activity-summary">{[['누적 플레이',summary.all],['최근 7일',summary.week],['최근 30일',summary.month],['선택 기간',summary.selected]].map(([label,n])=><div key={label}><span>{label}</span><strong>{time(n)}</strong></div>)}</div>
 <div className="activity-stats"><div><span>플레이한 날짜</span><strong>{summary.days||0}일</strong></div><div><span>평균 세션</span><strong>{time(summary.averageSession)}</strong></div><div><span>가장 오래 플레이한 날</span><strong>{summary.longestDay?.day||'기록 없음'}</strong><small>{summary.longestDay?time(summary.longestDay.seconds):''}</small></div></div>
 <div className="activity-day-detail"><h3>{query.day} <span className="muted">· {time((history.dayGames||[]).reduce((s,g)=>s+g.seconds,0))}</span></h3><p className="small muted">선택 날짜의 전체 기록 · 날짜를 넘긴 세션은 날짜별로 나누어 합산합니다.</p>{history.dayGames?.length?<><RangeBars rows={history.dayGames.map(g=>({id:g.gameId,name:gameName(g.gameId),seconds:g.seconds}))} total={history.dayGames.reduce((s,g)=>s+g.seconds,0)}/><details><summary>실행 시간대 보기 ({history.sessions?.length||0}개)</summary><div className="activity-sessions">{history.sessions.map(s=><div key={s.id}><strong>{gameName(s.gameId)}</strong><span>{sessionTime(s.startedAt)} ~ {sessionTime(s.endedAt)}</span><span>세션 전체 {time(s.durationSeconds)}{s.estimated?' · 마지막 신호 기준 종료':''}</span></div>)}</div>{history.sessionsTruncated&&<p className="small muted">최근 100개 세션만 표시합니다. 합계에는 모든 세션이 포함됩니다.</p>}</details></>:<p className="muted">이 날짜에는 완료된 플레이 기록이 없어요.</p>}</div>
 <div className="activity-bottom-grid"><div><h3><Gamepad2 size={18}/> 많이 플레이한 게임</h3>{rankings.length?<RangeBars rows={rankings.map((g,i)=>({id:g.gameId,name:`${i+1}. ${gameName(g.gameId)}`,seconds:g.seconds}))} total={summary.selected}/>:<p className="muted">완료된 플레이 기록이 쌓이면 순위가 표시돼요.</p>}</div><div><h3>장르별 플레이</h3><RangeBars rows={Object.entries(genres).sort((a,b)=>b[1]-a[1]).map(([name,seconds])=>({id:name,name,seconds}))} total={summary.selected}/><p className="small muted">지원 게임의 고정 장르 분류를 사용합니다.</p></div></div>
 <Trend history={history} period={query.period} today={today}/><p className="small muted"><Clock3 size={13}/> 앱에서 감지한 지원 게임의 완료된 세션만 집계해요. 업그레이드 이전 기록은 소급되지 않습니다. 플레이 중인 세션은 종료 후 반영됩니다.</p></>:<div className="activity-empty"><CalendarDays size={32}/><p>{history?.allowed===false?'이 친구는 플레이 기록을 공개하지 않았거나 친구 관계가 해제되었어요.':'기록 서버에서 데이터를 확인하고 있어요.'}</p></div>}
 </section>;
}
