import React,{useEffect,useRef,useState} from 'react';
import {send} from './bridge';
export function Avatar({person={},chat={},size=38}){const p=(chat.profiles||[]).find(p=>p.id===person.id)||person;const src=chat.avatars?.[p.avatarPath]||'nyang-icon.png';return <img className="chat-avatar" style={{width:size,height:size}} src={src} alt="" onError={e=>{if(!e.currentTarget.src.endsWith('/nyang-icon.png'))e.currentTarget.src='nyang-icon.png';}}/>;}
export function RoomAvatar({room,chat,me}){if(room?.avatarPath&&chat.avatars?.[room.avatarPath])return <img className="chat-avatar" src={chat.avatars[room.avatarPath]} alt=""/>;if(room?.kind==='group')return <span className="chat-group-avatar">{(room.members||[]).slice(0,4).map(p=><Avatar key={p.id} person={p} chat={chat} size={19}/>)}</span>;return <Avatar person={room?.members?.find(m=>m.id!==me)||{}} chat={chat}/>;}
export function AvatarEditor({room,onClose,chat}){
 const [photo,setPhoto]=useState(null),[zoom,setZoom]=useState(1),[pos,setPos]=useState({x:0,y:0}),[error,setError]=useState('');const preview=useRef(null),drag=useRef(null),url=useRef(null);
 useEffect(()=>()=>{if(url.current)URL.revokeObjectURL(url.current);},[]);
 function paint(canvas,size){if(!photo||!canvas)return;canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d'),scale=Math.max(size/photo.width,size/photo.height)*zoom,w=photo.width*scale,h=photo.height*scale;ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);ctx.drawImage(photo,(size-w)/2+pos.x*(w-size)/2,(size-h)/2+pos.y*(h-size)/2,w,h);}
 useEffect(()=>{paint(preview.current,224);},[photo,zoom,pos]);
 const clamp=n=>Math.max(-1,Math.min(1,n));
 async function choose(file){setError('');if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('PNG/JPG/WebP, 10MB 이하 이미지를 선택해 주세요.');return;}if(url.current)URL.revokeObjectURL(url.current);url.current=URL.createObjectURL(file);const img=new Image();img.onload=()=>{if(img.width>8192||img.height>8192){setError('가로·세로 8192픽셀 이하 이미지를 선택해 주세요.');return;}setPhoto(img);setZoom(1);setPos({x:0,y:0});};img.onerror=()=>setError('이미지를 읽을 수 없어요.');img.src=url.current;}
 function save(){const canvas=document.createElement('canvas');paint(canvas,256);const image=canvas.toDataURL('image/jpeg',.86);send('chat.avatar',{room:room||'',image});onClose();}
 return <div className="chat-modal-shade"><section className="card chat-modal" role="dialog" aria-modal="true" aria-label="프로필 이미지 편집"><h2>{room?'그룹 이미지':'프로필 이미지'} 변경</h2><label>이미지 파일<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>choose(e.target.files?.[0])}/></label><div className="avatar-crop-area"><canvas ref={preview} aria-label="원형 자르기 미리보기" onPointerDown={e=>{if(!photo)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,pos};}} onPointerMove={e=>{if(!drag.current||!photo)return;const s=Math.max(224/photo.width,224/photo.height)*zoom;setPos({x:clamp(drag.current.pos.x+(e.clientX-drag.current.x)*2/Math.max(1,photo.width*s-224)),y:clamp(drag.current.pos.y+(e.clientY-drag.current.y)*2/Math.max(1,photo.height*s-224))});}} onPointerUp={()=>drag.current=null}/></div>{!photo&&<p className="small muted">이미지를 고른 뒤 원형 안에서 드래그해 위치를 맞추세요.</p>}<label>확대 / 축소<input type="range" min="1" max="3" step=".01" value={zoom} disabled={!photo} onChange={e=>setZoom(Number(e.target.value))}/></label>{['x','y'].map(axis=><label key={axis}>{axis==='x'?'가로 위치':'세로 위치'}<input type="range" min="-1" max="1" step=".01" value={pos[axis]} disabled={!photo} onChange={e=>setPos({...pos,[axis]:Number(e.target.value)})}/></label>)}<p className="small muted">저장할 때 256×256 JPG로 줄여 전송합니다. 원본 이미지는 전송하지 않습니다.</p>{error&&<p role="alert">{error}</p>}<div className="chat-actions"><button className="button secondary" onClick={onClose}>취소</button><button className="button" disabled={!photo||chat.busy} onClick={save}>이미지 저장</button></div></section></div>;
}
