import React,{useEffect,useRef,useState} from 'react';
import {MessageCircle,Users,Send,Plus,Bell,BellOff,Settings,X} from 'lucide-react';
import {send} from './bridge';import {prepareChatImage,ChatImage} from './ChatImage';import {Status} from './FriendsPage';import {Avatar,RoomAvatar,AvatarEditor} from './ChatProfile';import './chat.css';
export const roomName=(r,me)=>r.kind==='group'?r.name:r.members?.find(m=>m.id!==me)?.nickname||'1:1 대화';
export function shouldSendEnter(e,composing=false){return e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!e.nativeEvent?.isComposing&&e.keyCode!==229&&e.nativeEvent?.keyCode!==229&&!composing;}
export function ChatOptions({view={}}){return <section className="card friends-options"><span className="eyebrow">CHAT NOTIFICATIONS</span><h2>채팅 알림</h2><label className="friend-toggle"><span>Windows에서 새 메시지 알림 받기</span><input type="checkbox" checked={view.notifications!==false} onChange={e=>send('chat.settings',{enabled:e.target.checked})}/></label><p className="small muted">알림을 꺼도 메시지와 읽지 않은 메시지 수는 계속 갱신됩니다. 현재 보고 있는 채팅방은 알리지 않습니다. 앱이 트레이에서 실행 중이어야 하며 Windows 알림 설정과 방해 금지 모드가 적용됩니다.</p></section>;}
export function ChatPage({view={},friends={}}){
 const [draft,setDraft]=useState(''),[pending,setPending]=useState(null),[group,setGroup]=useState(false),[manage,setManage]=useState(false),[avatar,setAvatar]=useState(false),[name,setName]=useState(''),[picked,setPicked]=useState([]),[invite,setInvite]=useState('');
 const [attachment,setAttachment]=useState(null),[imageBusy,setImageBusy]=useState(false),[imageError,setImageError]=useState(''),[lightbox,setLightbox]=useState(null);const fileInput=useRef(null),selection=useRef(0);
 const composing=useRef(false),sending=useRef(false),list=useRef(null),atBottom=useRef(true),older=useRef(null),active=useRef(null),groupNonce=useRef(null);
 const me=friends.me?.id,rooms=view.rooms||[],room=rooms.find(r=>r.id===view.room),members=room?.members||[],other=members.find(m=>m.id!==me),presence=(friends.friends||[]).find(f=>f.id===other?.id);
 useEffect(()=>{send('chat.visible',{visible:true});const focus=()=>{if(atBottom.current&&active.current)send('chat.read',active.current);};window.addEventListener('focus',focus);return()=>{send('chat.visible',{visible:false});window.removeEventListener('focus',focus);};},[]);
 useEffect(()=>{setDraft('');setAttachment(null);setImageError('');setLightbox(null);setImageBusy(false);selection.current++;setPending(null);sending.current=false;atBottom.current=true;older.current=null;setManage(false);setGroup(false);},[view.room]);
 useEffect(()=>{if(!pending)return;if(view.sentId===pending.id){setDraft(v=>v===pending.body?'':v);if(pending.data)setAttachment(v=>v?.data===pending.data?null:v);setPending(null);sending.current=false;}else if(view.failedId===pending.id)sending.current=false;},[view.sentId,view.failedId,pending]);
 const messages=view.messages||[];const last=messages.at(-1);active.current=last?{room:view.room,seq:last.seq}:null;
 useEffect(()=>{if(!list.current)return;if(older.current&&(messages[0]?.id!==older.current.firstId||(!view.busy&&!view.loadingOlder))){list.current.scrollTop=list.current.scrollHeight-older.current.height+older.current.top;older.current=null;}else if(atBottom.current)list.current.scrollTop=list.current.scrollHeight;if(document.hasFocus()&&atBottom.current&&active.current)send('chat.read',active.current);},[view]);
 async function chooseImage(file){if(!file||sending.current)return;const version=++selection.current;setImageBusy(true);setImageError('');try{const image=await prepareChatImage(file);if(version===selection.current){setAttachment(image);setPending(null);}}catch(e){if(version===selection.current)setImageError(e.message);}finally{if(version===selection.current)setImageBusy(false);}}
 function sendPending(p){sending.current=true;send(p.data?'chat.image':'chat.send',p);}
 function submit(e){e?.preventDefault();if(!room||(!draft.trim()&&!attachment)||sending.current||imageBusy)return;const data=attachment?.data;const p=pending?.body===draft&&pending.room===room.id&&pending.data===data?pending:{id:crypto.randomUUID(),room:room.id,body:draft,...(data?{data}:{})};setPending(p);sendPending(p);}
 function loadOlder(){if(view.busy||view.loadingOlder||!view.hasMore||!list.current||older.current)return;older.current={height:list.current.scrollHeight,top:list.current.scrollTop,firstId:messages[0]?.id};send('chat.older');}
 function onScroll(){if(!list.current)return;atBottom.current=list.current.scrollHeight-list.current.scrollTop-list.current.clientHeight<50;if(list.current.scrollTop<20)loadOlder();if(atBottom.current&&document.hasFocus()&&active.current)send('chat.read',active.current);}
 function create(e){e.preventDefault();if(!name.trim()||!picked.length)return;if(!groupNonce.current)groupNonce.current=crypto.randomUUID();send('chat.group',{id:groupNonce.current,name,users:picked});}
 const groupMembers=members.map(m=>({...m,...(friends.friends||[]).find(f=>f.id===m.id),...(m.id===me?{status:friends.localStatus,gameId:friends.gameId,gameStartedAt:friends.gameStartedAt}:{})}));
 return <div className="messenger-page"><div className="friends-heading"><span className="eyebrow">A LITTLE CLOSER</span><h1>채팅</h1><p role="status"><i className={'chat-connection '+(view.connected?'online':'')}/>{view.message||'친구 프로필을 등록하면 대화를 시작할 수 있어요.'}</p></div><div className="messenger-layout"><section className="card conversation-list"><div className="between"><h2>최근 대화</h2><button className="button secondary" disabled={!me} onClick={()=>{setGroup(true);setName('');setPicked([]);groupNonce.current=null;}}><Plus size={16}/>새 그룹</button></div>{!rooms.length&&<p className="muted">친구 탭에서 메시지를 눌러 첫 대화를 시작하세요.</p>}{rooms.map(r=><button className={'conversation-row '+(r.id===view.room?'selected':'')} key={r.id} onClick={()=>send('chat.open',{room:r.id})}><RoomAvatar room={r} chat={view} me={me}/><span className="conversation-copy"><strong>{roomName(r,me)}</strong><span>{r.latest?(r.kind==='group'?`${r.members?.find(m=>m.id===r.latest.sender)?.nickname||'이전 참여자'}: `:'')+r.latest.body:'대화를 시작해 보세요.'}</span><time>{r.latest?new Date(r.latest.sent_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):''}</time></span><span className="conversation-flags">{!r.notifications&&<BellOff size={13}/>} {r.unread>0&&<b className="unread-badge">{r.unread>99?'99+':r.unread}</b>}</span></button>)}</section>
 <section className="card messenger-chat">{room?<><div className="messenger-header"><RoomAvatar room={room} chat={view} me={me}/><div className="messenger-heading"><h2>{roomName(room,me)}</h2>{room.kind==='direct'?<Status friend={presence||{status:'offline'}} stale={friends.stale}/>:<span className="small muted">참여자 {members.length}명</span>}</div><button className="button secondary" aria-label="채팅방 설정" onClick={()=>{setManage(v=>!v);setName(room.name);}}><Settings size={17}/></button></div>
 {manage&&<div className="room-settings"><label className="friend-toggle"><span>이 채팅방 알림</span><input type="checkbox" checked={room.notifications} onChange={e=>send('chat.manage',{room:room.id,action:'notify',enabled:e.target.checked})}/></label>{room.kind==='group'&&<><form className="chat-actions" onSubmit={e=>{e.preventDefault();send('chat.manage',{room:room.id,action:'rename',name});}}><label>그룹 이름<input maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label><button className="button secondary" disabled={view.busy||!name.trim()}>이름 저장</button></form><button className="button secondary" onClick={()=>setAvatar(true)}>그룹 이미지 변경</button><div className="group-members">{groupMembers.map(m=><div key={m.id}><Avatar person={m} chat={view} size={28}/><span>{m.nickname}<Status friend={m}/></span></div>)}</div><form className="chat-actions" onSubmit={e=>{e.preventDefault();send('chat.manage',{room:room.id,action:'invite',user:invite});setInvite('');}}><label>친구 초대<select value={invite} onChange={e=>setInvite(e.target.value)}><option value="">초대할 친구</option>{(friends.friends||[]).filter(f=>!members.some(m=>m.id===f.id)).map(f=><option key={f.id} value={f.id}>{f.nickname}</option>)}</select></label><button className="button secondary" disabled={!invite||view.busy||members.length>=20}>초대</button></form><button className="button secondary" disabled={view.busy} onClick={()=>{if(window.confirm('그룹에서 나갈까요? 다시 초대받기 전에는 대화를 볼 수 없어요.'))send('chat.manage',{room:room.id,action:'leave'});}}>그룹 나가기</button></>}</div>}
 <div ref={list} className="messenger-messages" role="log" aria-label="채팅 메시지" onScroll={onScroll}>{view.hasMore&&<button className="button secondary older-messages" disabled={view.busy||view.loadingOlder} onClick={loadOlder}>{view.loadingOlder?'불러오는 중…':'이전 메시지 더 보기'}</button>}{messages.map(m=>{const person=members.find(p=>p.id===m.sender)||{nickname:'이전 참여자',id:m.sender},mine=m.sender===me,read=members.filter(p=>p.id!==me).every(p=>p.lastRead>=m.seq);return <article className={'messenger-message '+(mine?'mine':'')} key={m.id}><Avatar person={person} chat={view} size={30}/><div><strong>{mine?'나':person.nickname}</strong>{m.image_path&&<ChatImage src={view.images?.[m.image_path]} onOpen={setLightbox} onReload={()=>send('chat.images')}/>}<p>{m.image_path&&m.body==='[사진]'?'':m.body}</p><time>{new Date(m.sent_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}{mine?' · '+(read?'읽음':'전송됨'):''}</time></div></article>;})}{!messages.length&&<p className="chat-empty-copy">가벼운 한마디로 시작해 보세요.</p>}</div>
 {pending&&<div className="chat-send-status" role="status">{view.failedId===pending.id?<><span>전송 실패 · {pending.data?'사진 · ':''}{pending.body.slice(0,40)}</span><button className="button secondary" disabled={view.busy} onClick={()=>sendPending(pending)}>다시 보내기</button></>:<span>전송 중…</span>}</div>}
 {attachment&&<div className="chat-attachment-preview"><img src={attachment.data} alt="전송 전 사진 미리보기"/><span>{attachment.name}<small>{attachment.width} × {attachment.height} · 전송 전 미리보기</small></span><button type="button" className="button secondary" disabled={sending.current} onClick={()=>{selection.current++;setAttachment(null);setPending(null);}}>사진 제거</button></div>}
 {imageError&&<p role="alert">{imageError}</p>}
 <form className="chat-compose" onSubmit={submit}><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{chooseImage(e.target.files?.[0]);e.target.value='';}}/><button type="button" className="button secondary" aria-label="사진 첨부" disabled={imageBusy||!!pending&&view.failedId!==pending.id} onClick={()=>fileInput.current?.click()}>{imageBusy?'준비 중…':'사진'}</button><label className="sr-only" htmlFor="messenger-input">메시지</label><textarea id="messenger-input" onPaste={e=>{const file=[...(e.clipboardData?.files||[])].find(f=>f.type.startsWith('image/'));if(file){e.preventDefault();chooseImage(file);}}} rows={2} value={draft} maxLength={1000} placeholder="메시지를 입력하세요" onChange={e=>setDraft(e.target.value)} onCompositionStart={()=>composing.current=true} onCompositionEnd={()=>composing.current=false} onKeyDown={e=>{if(shouldSendEnter(e,composing.current)){e.preventDefault();submit();}}}/><button className="button" disabled={view.busy||imageBusy||(!draft.trim()&&!attachment)||!!pending&&view.failedId!==pending.id}><Send size={17}/>전송</button></form><div className="chat-composer-note"><span>Enter 전송 · Shift+Enter 줄바꿈 · 이미지 붙여넣기</span><span>{draft.length}/1000</span></div></>:<div className="friends-empty"><MessageCircle size={38}/><h2>대화를 선택해 주세요</h2><p>친구와 가볍게, 게임 이야기를 나눠요.</p></div>}</section></div><ChatOptions view={view}/><p className="small muted">작성 중인 내용은 전송 전까지 PC에만 머물러요. 채팅은 서버에 저장되며 종단 간 암호화는 제공하지 않습니다.</p>{view.uploadState&&<p role="status">{view.uploadState}</p>}
 {group&&<div className="chat-modal-shade"><form className="card chat-modal" onSubmit={create} role="dialog" aria-modal="true" aria-label="새 그룹 만들기"><h2>새 그룹 만들기</h2><label>그룹 이름<input value={name} maxLength={40} onChange={e=>setName(e.target.value)} placeholder="금요일 게임팟"/></label><div className="group-pick">{(friends.friends||[]).map(f=><label key={f.id}><Avatar person={f} chat={view}/><span>{f.nickname}</span><input type="checkbox" checked={picked.includes(f.id)} disabled={!picked.includes(f.id)&&picked.length>=19} onChange={e=>setPicked(e.target.checked?[...picked,f.id]:picked.filter(id=>id!==f.id))}/></label>)}</div><p className="small muted">나를 포함해 최대 20명 · 선택한 친구를 그룹에 초대합니다.</p><div className="chat-actions"><button type="button" className="button secondary" onClick={()=>setGroup(false)}>취소</button><button className="button" disabled={view.busy||!name.trim()||!picked.length}>그룹 만들기</button></div></form></div>}
 {lightbox&&<div className="chat-modal-shade chat-image-lightbox" role="dialog" aria-modal="true" aria-label="사진 크게 보기" onClick={()=>setLightbox(null)} onKeyDown={e=>{if(e.key==='Escape')setLightbox(null);}}><button className="button" autoFocus onClick={()=>setLightbox(null)}>닫기</button><img src={lightbox} alt="채팅 사진 확대" onClick={e=>e.stopPropagation()}/></div>}
 {avatar&&room&&<AvatarEditor room={room.id} chat={view} onClose={()=>setAvatar(false)}/>}
 </div>;
}
