import React,{useEffect,useState} from 'react';
import {Link2,Unlink,RefreshCw,KeyRound,ExternalLink,Shield,ChevronDown,TrendingUp,Target} from 'lucide-react';
import {send} from './bridge';
const number=v=>v==null?'—':Number(v).toLocaleString('ko-KR',{maximumFractionDigits:1});
const date=v=>{if(!v)return '시간 정보 없음';const d=new Date(v);return Number.isNaN(d.valueOf())?v:d.toLocaleString('ko-KR');};
const delta=v=>v==null?'RP 변화 미제공':`${v>0?'+':''}${number(v)} RP`;
const average=(list,key)=>{const values=list.map(m=>m[key]).filter(v=>v!=null);return values.length?values.reduce((a,b)=>a+b,0)/values.length:null;};
const duration=v=>v==null?'시간 미제공':`${Math.floor(v/60)}분 ${v%60}초`;
const states={disconnected:'미연결',restoring:'연결 복원 중',connected:'연결됨',key:'API 키 필요',forbidden:'접근 확인 필요',rateLimit:'호출 제한',notFound:'계정/기록 없음',network:'네트워크 오류',service:'API 응답 오류',format:'응답 형식 확인',storage:'저장 확인 필요',input:'닉네임 확인',siteBlocked:'사이트 조회 중지'};
function Button({children,secondary=false,...props}){return <button className={'button '+(secondary?'secondary':'')} {...props}>{children}</button>;}
function Heading({small,children}){return <div className="section-heading"><div><span className="eyebrow">{small}</span><h2>{children}</h2></div></div>;}
export function EternalSummary({account}){
 const a=account,d=a?.data,m=d?.matches?.find(m=>m.mode===3&&m.season===d.seasonId);
 if(!a?.connected)return <p className="muted">계정을 연결하면 실제 RP와 최근 경기를 확인할 수 있어요.</p>;
 return <div className="er-home-summary"><strong>{d?.nickname||'계정 확인 중'}</strong><span>{d?.rp==null?'현재 시즌 RP 확인 대기':`${number(d.rp)} RP`}</span>{m&&<small className={m.delta>0?'positive':m.delta<0?'negative':'muted'}>{delta(m.delta)}</small>}{a.stale&&<small>마지막 정상 기록 · {date(d?.updatedAt)}</small>}</div>;
}
function Rank({data:d,preview=false}){
 const recent=d.matches?.find(m=>m.mode===3&&m.season===d.seasonId);
 return <section className={'card er-rank '+(preview?'er-preview':'')}><div className="er-rank-symbol"><Shield size={38}/></div><div className="er-rank-copy"><span className="eyebrow">{preview?'FOUND ACCOUNT':d.source==='hippy'?'HIPPYGG / SEASON STATS':d.source==='ercraft'?'ERCraft / RANKED SQUAD':'OFFICIAL / RANKED SQUAD'}</span><h2>{d.nickname}</h2><p>{d.seasonName||'현재 시즌 확인 불가'}</p><div className="value er-rp">{d.rp==null?'RP 정보 없음':`${number(d.rp)} RP`}</div><h3>{d.tier||'티어명 미제공'}</h3><p className="small muted">{d.rankMessage}</p>{d.metadataMessage&&<p className="small muted">{d.metadataMessage}</p>}</div><div className="er-rank-side">{recent&&<span className={'badge '+(recent.delta>0?'positive':recent.delta<0?'negative':'')}>최근 랭크 · {delta(recent.delta)}</span>}<span>시즌 경기 {number(d.seasonGames)}회</span><span>시즌 1위 {number(d.seasonWins)}회</span><span>전체 순위 {d.ranking>0?number(d.ranking)+'위':'정보 없음'}</span>{preview&&<Button onClick={()=>send('eternal.connect')}><Link2 size={16}/>이 계정 연결</Button>}</div></section>;
}
function Trend({matches}){
 const rows=matches.filter(m=>m.mode===3&&m.delta!=null).slice(0,10).reverse();if(!rows.length)return null;
 const max=Math.max(1,...rows.map(m=>Math.abs(m.delta)));
 return <section className="card"><Heading small="RANKED / RP CHANGE">경기별 RP 변화</Heading><div className="er-trend" aria-label="최근 경기별 RP 변화">{rows.map(m=><div key={m.id}><span className={m.delta<0?'negative':'positive'}>{m.delta>0?'+':''}{number(m.delta)}</span><div className="er-trend-track"><i style={{height:Math.max(2,Math.abs(m.delta)/max*64),background:m.delta<0?'var(--negative)':'var(--positive)'}}/></div><small>#{number(m.rank)}</small></div>)}</div><p className="small muted">오래된 경기 → 최근 경기 · 조회 기록에 RP 변화값이 제공된 랭크 경기만 표시해요.</p></section>;
}
function Match({m}){
 return <details className="card er-match"><summary><div className={'er-place '+(m.rank===1?'positive':'')}><small>PLACE</small><strong>{m.rank==null?'—':`#${m.rank}`}</strong></div><div className="er-match-name"><h3>{m.character}</h3><span className="small muted">{m.mode===3?'랭크':m.mode===2?'일반':`모드 ${m.mode??'미제공'}`} · {date(m.startedAt)}</span></div><div className="er-kda"><span>{number(m.kills)} Kill</span><span>{number(m.assists)} Assist</span></div><strong className={m.delta>0?'positive':m.delta<0?'negative':'muted'}>{delta(m.delta)}</strong><span className="small muted">플레이 {duration(m.seconds)}</span><ChevronDown size={18}/></summary><dl className="er-detail">{[['캐릭터 레벨',m.level],['플레이어 피해량',m.damage],['받은 피해량',m.received],['회복량',m.healing],['팀 킬',m.teamKills]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{number(value)}</dd></div>)}</dl><p className="small muted">경기 ID {m.id} · 상세 통계는 이미 받은 경기 기록을 사용해 추가 요청하지 않아요.</p></details>;
}
export function EternalReturnAccount({account}){
 const a=account||{},d=a.data,isDak=a.source!=='api',isHippy=a.source==='hippy',siteName=isHippy?'히피지지':'ERCraft',[nickname,setNickname]=useState(''),[mode,setMode]=useState('ranked');
 useEffect(()=>{send('eternal.refresh',{manual:false});},[]);
 const received=d?.matches||[],matches=received.filter(m=>mode==='all'||m.mode===3),ranks=matches.filter(m=>m.rank!=null),gains=matches.filter(m=>m.mode===3&&m.delta!=null);
 const groups=Object.entries(matches.reduce((all,m)=>{(all[m.character]??=[]).push(m);return all;},{})).sort((a,b)=>b[1].length-a[1].length);
 return <div className="er-account">
  <section className="card"><div className="section-heading"><div><span className="eyebrow">ETERNAL RETURN / ACCOUNT</span><h2>이터널 리턴 계정</h2></div><span className={'badge '+(a.connected&&!a.stale?'positive':'')}>{a.busy?'기록 조회 중…':states[a.state]||'연결 대기'}</span></div>
   <p role="status">{a.message||'닉네임으로 공개 전적을 연결해 주세요.'}</p>
   {!a.connected&&<label className="er-filter">조회 방식<select value={a.source||'ercraft'} disabled={a.busy} onChange={e=>send('eternal.source',{source:e.target.value})}><option value="ercraft">ERCraft · 키 없이 연결</option><option value="hippy">히피지지 · 시즌 통계</option><option value="api">공식 API · 개인 키 사용</option></select></label>}
   {!a.connected&&<form className="er-search" onSubmit={e=>{e.preventDefault();send('eternal.search',{nickname:nickname.trim()});}}><label htmlFor="er-nickname">게임 닉네임<input id="er-nickname" maxLength={512} autoComplete="off" value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="현재 게임 닉네임"/></label><Button disabled={(!isDak&&!a.hasKey)||a.busy||!nickname.trim()}><Link2 size={16}/>계정 찾기</Button></form>}
   <div className="account-actions"><Button secondary onClick={()=>send('eternal.hippy')}>히피지지 전적 검색<ExternalLink size={16}/></Button>{!isDak&&<><Button secondary disabled={a.busy} onClick={()=>send('eternal.key')}><KeyRound size={16}/>{a.hasKey?'API 키 변경':'API 키 등록'}</Button><Button secondary onClick={()=>send('eternal.portal')}><ExternalLink size={16}/>공식 개발자 포털</Button></>}{isDak&&<Button secondary onClick={()=>send('eternal.site')}>{siteName}에서 확인<ExternalLink size={16}/></Button>}{a.connected&&<Button disabled={a.busy} onClick={()=>send('eternal.refresh',{manual:true})}><RefreshCw size={16}/>{isDak?'사이트 기록 다시 읽기':'새로고침'}</Button>}{(a.connected||a.hasKey)&&<Button secondary onClick={()=>send('eternal.disconnect')}><Unlink size={16}/>연결 해제</Button>}</div>
   <p className="small muted">{isHippy?'출처: 히피지지 · 공개 페이지의 시즌 통계예요. 개별 경기 목록은 제공하지 않아요.':isDak?'출처: ERCraft · 공개 전적 조회(실험적). 사이트에 저장된 값을 표시하며 최신 반영은 ERCraft 갱신 상태에 따라 달라져요.':'API 키는 별도 Windows 입력창에서 등록해요. 이 Windows 계정에 암호화 저장되며 웹 화면에는 전달되지 않아요.'}</p>{isDak&&d&&<p className="small muted">{siteName} 기록 갱신 · {d.sourceUpdatedAt?date(d.sourceUpdatedAt):'시각 미제공'}</p>}{d?.updatedAt&&<p className="small muted">{a.stale?'마지막 정상 기록':'마지막 업데이트'} · {date(d.updatedAt)}{a.stale?' · 최신 상태가 아닐 수 있어요.':''}</p>}
  </section>
  <p className="small muted">동일 데이터는 최소 15분 동안 캐시를 사용해요. 호출 제한 시 지정된 시간만큼 대기하며 접근 차단 시 해당 사이트 조회를 중단해요.</p>
  {a.preview&&<Rank data={a.preview} preview/>}
  {a.connected&&d&&isHippy&&<><Rank data={d}/><HippySeason data={d}/></>}{a.connected&&d&&!isHippy&&<><Rank data={d}/><section className="card"><div className="section-heading"><div><span className="eyebrow">RECENT SAMPLE / NOT SEASON TOTAL</span><h2>최근 {matches.length}경기 요약</h2></div><label className="er-filter">기록 범위<select value={mode} onChange={e=>setMode(e.target.value)}><option value="ranked">랭크 경기</option><option value="all">전체 모드</option></select></label></div><p className="small muted">최근 수신 {received.length}경기 중 선택한 범위예요. 시즌 전체 통계가 아니며 닉네임 변경 이전 기록은 조회 결과에서 제외될 수 있어요.</p><div className="er-stat-grid">{[['평균 순위',number(average(matches,'rank'))+'위'],['Top 3',`${ranks.filter(m=>m.rank<=3).length} / ${ranks.length}경기`],['평균 Kill',number(average(matches,'kills'))],['랭크 RP 변화',gains.length?delta(gains.reduce((v,m)=>v+m.delta,0)):'미제공']].map(([label,value])=><div key={label}><span className="small muted">{label}</span><strong>{value}</strong></div>)}</div>{gains.length>0&&<p className="small muted">RP 합계는 변화값이 제공된 랭크 {gains.length}경기 기준이에요.</p>}</section><Trend matches={matches}/><Heading small="RECENT MATCHES">최근 경기</Heading>{matches.length?matches.map(m=><Match key={m.id} m={m}/>):<section className="card"><Target/><h3>표시할 경기 기록이 없어요</h3><p>아직 플레이하지 않았거나 전적 반영 전일 수 있어요. 종료 후 잠시 기다려 주세요.</p></section>}<section className="card"><Heading small="CHARACTER / RECENT SAMPLE">최근 사용 캐릭터</Heading><div className="er-character-grid">{groups.map(([name,rows])=>{const ranked=rows.filter(m=>m.rank!=null),wins=ranked.filter(m=>m.rank===1).length;return <div className="er-character" key={name}><h3>{name}</h3><strong>{rows.length}경기</strong><p>1위 {wins}회 · 승률 {ranked.length?number(wins/ranked.length*100)+'%':'미제공'}</p><p>평균 순위 {number(average(rows,'rank'))}위 · 평균 Kill {number(average(rows,'kills'))}</p><small className="muted">순위 통계: 순위가 제공된 {ranked.length}경기 기준</small></div>;})}</div>{!groups.length&&<p>경기 기록이 모이면 표시돼요.</p>}</section></>}
 </div>;
}


function HippySeason({data:d}){return <><section className="card"><Heading small="SEASON TOTAL">시즌 통계</Heading><div className="er-stat-grid">{[['평균 순위',number(d.seasonAverageRank)+'위'],['승률',d.seasonGames?number(d.seasonWins/d.seasonGames*100)+'%':'—'],['평균 Kill',number(d.seasonAverageKills)],['평균 Assist',number(d.seasonAverageAssists)]].map(([label,value])=><div key={label}><span className="small muted">{label}</span><strong>{value}</strong></div>)}</div><p className="small muted">히피지지에서 제공한 시즌 전체 스쿼드 랭크 통계예요. 개별 경기와 경기별 RP 변화는 제공하지 않아요.</p></section><section className="card"><Heading small="CHARACTER / SEASON TOTAL">시즌 사용 캐릭터</Heading><div className="er-character-grid">{(d.seasonCharacters||[]).map((c,i)=><div className="er-character" key={i}><h3>{c.name}</h3><strong>{number(c.games)}경기</strong><p>1위 {number(c.wins)}회 · 승률 {c.games?number(c.wins/c.games*100)+'%':'—'}</p><p>평균 순위 {number(c.averageRank)}위</p></div>)}</div></section></>;}
