import {Avatar,AvatarEditor} from './ChatProfile';
import React,{useEffect,useRef,useState} from 'react';
import {Users,Gamepad2,MessageCircle,Send,UserPlus,Shield,Settings} from 'lucide-react';
import {send,duration} from './bridge';
import './friends.css';
import {ActivityDashboard,historyQuery} from './ActivityDashboard';
const names={genshin:'원신',eternal:'이터널 리턴',league:'League of Legends',valorant:'VALORANT'};
const labels={gaming:'게임 중',online:'온라인',away:'자리비움',offline:'오프라인'};
const priority={gaming:0,online:1,away:2,offline:3};
export function Status({friend,stale=false}){const state=stale?'offline':friend.status||'offline';return <span className={'friend-status friend-state-'+state}>{state==='gaming'?<Gamepad2 size={16}/>:<i/>}{state==='gaming'?`${names[friend.gameId]||'게임'} 플레이 중 · ${duration(Math.max(0,(Date.now()-Date.parse(friend.gameStartedAt))/1000))}`:labels[state]}{stale?' · 재연결 대기':''}</span>}
export function FriendsOptions({view={}}){const o=view.options||{shareGame:true,appearOffline:false,autoAway:true,awayMinutes:10};const change=patch=>send('friends.options',{...o,...patch});return <section className="card friends-options"><span className="eyebrow">YOUR PRIVACY</span><h2>친구에게 보이는 나</h2>{[['shareGame','친구에게 게임 활동 공유'],['appearOffline','오프라인으로 표시'],['autoAway','자리비움 자동 전환']].map(([key,label])=><label className="friend-toggle" key={key}><span>{label}</span><input type="checkbox" checked={o[key]} onChange={e=>change({[key]:e.target.checked})}/></label>)}<label className="friend-toggle"><span>플레이 기록 및 통계 공유</span><input type="checkbox" checked={!!o.shareHistory} onChange={e=>send('friends.history.privacy',{share:e.target.checked})}/></label><p className="small muted">공유 OFF여도 내 게임 기록은 저장되며 본인만 볼 수 있어요. ON이면 승인한 친구에게 과거 기록도 공개합니다. 현재 게임 활동 공유와 별개입니다.{view.historyPending?' · 서버 반영 대기 중':''}</p><label>자리비움 전환 시간<select value={o.awayMinutes} disabled={!o.autoAway} onChange={e=>change({awayMinutes:Number(e.target.value)})}>{[5,10,15,30].map(m=><option key={m} value={m}>{m}분</option>)}</select></label><p className="small muted">입력이 없는 시간만 PC 안에서 확인합니다. 게임 중에는 자리비움보다 게임 상태를 우선합니다. 오프라인 표시는 접속 상태만 숨기며, 직접 보낸 메시지는 상대에게 전달됩니다.</p></section>}
export function FriendsPage({view={},chat={}}){
 const [nickname,setNickname]=useState(''),[code,setCode]=useState(''),[avatar,setAvatar]=useState(false);
 useEffect(()=>{send('friends.visible',{visible:true});return()=>send('friends.visible',{visible:false});},[]);
 useEffect(()=>{if(view.me?.nickname)setNickname(view.me.nickname);},[view.me?.nickname]);
 const friends=[...(view.friends||[])].sort((a,b)=>(priority[a.status]??3)-(priority[b.status]??3)||a.nickname.localeCompare(b.nickname,'ko'));
 const activityProfile=view.historyUser===view.me?.id?view.me:friends.find(f=>f.id===view.historyUser);
 return <div className="friends-page"><section className="friends-heading"><span className="eyebrow">TOGETHER, IN YOUR OWN SPACE</span><h1>함께하는 플레이</h1><p>친구의 지금과 플레이 기록을 만나보세요.</p></section>
 <section className="card friends-identity"><div><div className="friend-profile-avatar"><Avatar person={view.me||{}} chat={chat} size={64}/><div><span className="eyebrow">MY PROFILE</span><h2>{view.me?.nickname||'나의 친구 프로필'}</h2>{view.me?<><strong className="friend-code">{view.me.code}</strong><Status friend={{status:view.localStatus,gameId:view.gameId,gameStartedAt:view.gameStartedAt}}/></>:<p className="muted">닉네임을 정하고 친구 코드를 만들어 보세요.</p>}</div></div>{view.me&&<div className="friend-profile-actions"><button className="button secondary" onClick={()=>setAvatar(true)}>프로필 이미지 변경</button><button className="button secondary" onClick={()=>{if(view.historyUser!==view.me.id)send('friends.history',historyQuery(view.me.id));}}>내 플레이 기록 보기</button></div>}</div><div className="friend-profile-form"><label>닉네임<input maxLength={24} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="친구에게 보일 이름"/></label><button className="button" disabled={view.busy||!nickname.trim()} onClick={()=>send('friends.profile',{nickname})}>{view.me?'프로필 저장':'친구 기능 시작'}</button><button className="button secondary" onClick={()=>send('friends.setup')}><Settings size={15}/>연결 설정</button></div></section>
 <p className="friends-notice" role="status">{view.message||'친구 서버 설정을 기다리고 있어요.'}{view.lastUpdated&&<span> · 마지막 확인 {new Date(view.lastUpdated).toLocaleTimeString('ko-KR')}</span>}</p>{chat.uploadState&&<p role="status" className="small muted">{chat.uploadState}</p>}
 {activityProfile&&<ActivityDashboard key={activityProfile.id} view={view} chat={chat} profile={activityProfile} status={<Status friend={activityProfile.id===view.me?.id?{status:view.localStatus,gameId:view.gameId,gameStartedAt:view.gameStartedAt}:activityProfile} stale={view.stale}/>}/>}
 <section className="card friends-list friends-only-list"><div className="between"><h2><Users size={22}/> 친구</h2><span className="small muted">{view.stale?'—':friends.filter(f=>f.status!=='offline').length} / {friends.length}</span></div><form className="friend-add" onSubmit={e=>{e.preventDefault();send('friends.request',{code});}}><label className="sr-only" htmlFor="friend-code">친구 코드</label><input id="friend-code" value={code} maxLength={24} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="NYANG-친구 코드"/><button className="button secondary" disabled={view.busy||!view.me||!code.trim()} aria-label="친구 요청"><UserPlus size={18}/></button></form>
 {(view.requests||[]).map(r=><div className="friend-request" key={r.id}><Avatar person={r} chat={chat} size={30}/><strong>{r.nickname}</strong><span className="small muted">{r.incoming?'친구 요청':'수락 대기'}</span>{r.incoming?<><button disabled={view.busy} className="button secondary" onClick={()=>send('friends.respond',{user:r.id,accept:true})}>수락</button><button disabled={view.busy} className="button secondary" onClick={()=>send('friends.respond',{user:r.id,accept:false})}>거절</button></>:<button disabled={view.busy} className="button secondary" onClick={()=>send('friends.remove',{user:r.id})}>취소</button>}</div>)}
 {friends.length?friends.map(f=><div className="friend-card-line" key={f.id}><button className={'friend-row '+(view.historyUser===f.id?'selected':'')} onClick={()=>{if(view.historyUser!==f.id)send('friends.history',historyQuery(f.id));}}><Avatar person={f} chat={chat}/><span><strong>{f.nickname}</strong><Status friend={f} stale={view.stale}/></span></button><button className="button secondary" disabled={chat.busy} onClick={()=>send('chat.direct',{user:f.id})}><MessageCircle size={16}/>메시지</button><button className="button secondary" disabled={view.busy} onClick={()=>{if(window.confirm('친구를 삭제할까요? 서로 상태와 1:1 대화를 볼 수 없게 됩니다.'))send('friends.remove',{user:f.id});}}>삭제</button></div>):<div className="friends-empty"><Users size={32}/><h3>첫 친구를 기다리고 있어요</h3><p>친구 코드를 입력하고 상대가 수락하면<br/>상태를 확인하고 대화할 수 있어요.</p></div>}</section>
 <FriendsOptions view={view}/><div className="privacy-note"><Shield size={18}/><p>친구에게는 허용한 게임 활동과 프로필만 공유해요.<br/>브라우저, 창 제목, 파일 이름, 화면, 입력 내용은 공유하지 않아요.</p></div>{avatar&&<AvatarEditor chat={chat} onClose={()=>setAvatar(false)}/>}</div>;
}
