import React,{useEffect,useState} from 'react';
import {send} from './bridge';
import {RefreshCw,Sparkles,Shield,Swords} from 'lucide-react';
const val=v=>v==null?'—':v;
const elementNames={Pyro:'불',Hydro:'물',Anemo:'바람',Electro:'번개',Dendro:'풀',Cryo:'얼음',Geo:'바위'};
function Portrait({src,name}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return <div className="character-portrait">{src&&!failed?<img src={src} alt={name||''} loading="lazy" onError={()=>setFailed(true)}/>:<Sparkles aria-label="이미지 없음"/>}</div>}
function Stats({items}){return items?.length?<dl className="character-stats-list">{items.map((s,i)=><div key={s.name+i}><dt>{s.name}</dt><dd>{s.value||'—'}</dd></div>)}</dl>:<p className="small muted">제공되는 스탯 정보가 없어요.</p>}
function Equipment({item}){return <div className="equipment-item"><div className="equipment-heading"><Portrait src={item.icon} name={item.name}/><div><h3>{item.name||'이름 미제공'}</h3><p>Lv.{val(item.level)}{item.refinement!=null?` · 재련 ${item.refinement}`:''}</p>{item.slot&&<p>{item.slot} · {item.set}</p>}</div></div><Stats items={item.stats}/></div>}
export function GenshinCharacters({account,characters}){
 const c=characters||{items:[],state:'idle'},[query,setQuery]=useState('');
 useEffect(()=>{if(account?.connected&&account?.selected)send('characters.load');},[account?.connected,account?.selected?.uid,account?.selected?.server]);
 const list=(c.items||[]).filter(x=>x.name?.toLowerCase().includes(query.toLowerCase()));const d=c.detail;
 return <section className="characters-section" aria-label="원신 캐릭터">
  <div className="section-heading"><div><span className="eyebrow">YOUR COMPANIONS / HOYOLAB</span><h2>함께하는 여행자들</h2></div><button className="button secondary" disabled={c.busy||!account?.connected} onClick={()=>send('characters.load',{manual:true})}><RefreshCw size={16}/>목록 새로고침</button></div>
  <p role="status" className="small muted">{c.message} {c.updatedAt&&` · 목록 갱신 ${new Date(c.updatedAt).toLocaleString('ko-KR')}`}{c.stale?' · 이전 데이터':''}</p>
  {!account?.connected&&<p>실시간 정보에서 계정 연결 상태를 확인해 주세요.</p>}
  <label className="character-search">캐릭터 찾기<input type="search" placeholder="이름으로 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label>
  {d&&<section className="card character-detail" aria-label="캐릭터 상세정보">
   <div className="section-heading"><div className="equipment-heading"><Portrait src={d.icon} name={d.name}/><div><span className="eyebrow">{elementNames[d.element]||d.element||'원소 미제공'}</span><h2>{d.name}</h2><p>Lv.{val(d.level)} · 호감도 {val(d.friendship)} · 운명의 자리 {val(d.constellation)}</p></div></div><button className="button secondary" disabled={c.busy} onClick={()=>send('characters.select',{id:d.id,manual:true})}><RefreshCw size={16}/>상세 갱신</button></div>
   <p className="small muted">실제 장비 정보 · {c.detailUpdatedAt?new Date(c.detailUpdatedAt).toLocaleString('ko-KR'):''}</p>
   <div className="two-grid"><div><h3><Swords size={17}/> 장착 무기</h3>{d.weapon?<Equipment item={d.weapon}/>:<p>무기 정보 미제공</p>}</div><div><h3>주요 스탯</h3><Stats items={d.stats}/></div></div>
   <h3 className="artifact-title"><Shield size={17}/> 성유물</h3><div className="artifact-grid">{d.artifacts?.length?d.artifacts.map((a,i)=><Equipment key={i} item={a}/>):<p>성유물 정보 미제공</p>}</div>
  </section>}
  {c.busy&&<p role="status">캐릭터 정보를 불러오는 중…</p>}
  <div className="character-grid">{list.map(x=><button className={'card character-tile '+(c.selectedId===x.id?'selected':'')} key={x.id} disabled={c.busy} onClick={()=>send('characters.select',{id:x.id})} aria-label={x.name+' 상세정보'}><Portrait src={x.icon} name={x.name}/><span className="eyebrow">{elementNames[x.element]||x.element||'원소 미제공'}</span><h3>{x.name||'이름 미제공'}</h3><p>Lv.{val(x.level)}</p><span className="small">운명의 자리 {val(x.constellation)} · 호감도 {val(x.friendship)}</span></button>)}</div>
  {!c.busy&&list.length===0&&<div className="card unavailable"><Sparkles/><p>{c.items?.length?'검색 결과가 없어요.':'조회된 캐릭터가 아직 없어요. 연결 상태를 확인하거나 새로고침해 주세요.'}</p></div>}
 </section>
}
export function OverlaySettings({data}){const s=data.settings.overlay||{autoShow:false,themeSync:true,hotkey:'G'};return <section className="card overlay-settings"><div className="section-heading"><div><span className="eyebrow">GAMING NAVIGATION</span><h2>게임 위의 작은 공간</h2></div></div><label className="toggle-row"><span>게임 실행 시 Gaming Bar 표시<small>보기 전용으로 시작하며 마우스 입력은 게임으로 통과해요.</small></span><input type="checkbox" role="switch" checked={s.autoShow} onChange={e=>send('overlay.settings',{autoShow:e.target.checked})}/></label><label className="hotkey-picker">표시 / 숨기기 단축키<span>Ctrl + <select aria-label="Gaming Bar 단축키" value={s.hotkey} onChange={e=>send('overlay.settings',{hotkey:e.target.value})}>{'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(k=><option key={k}>{k}</option>)}</select></span></label><p className="small muted">{data.overlayStatus||'단축키 상태 확인 중'}</p><div className="hud-designs" role="group" aria-label="Gaming Bar 디자인">{[['pink-capsule','Pink Capsule','핑크 캡슐 · 기본 디자인'],['rose-glass','Rose Glass','딥 로즈 · 핑크 포인트'],['midnight-lavender','Midnight Lavender','차콜 · 라벤더 포인트']].map(([id,name,desc])=><button key={id} type="button" aria-pressed={(s.design||'pink-capsule')===id} className={'hud-design '+id+((s.design||'pink-capsule')===id?' selected':'')} onClick={()=>send('overlay.settings',{design:id})}><span className="hud-swatch" aria-hidden="true">◉ 원신 <span>│ 레진 142/200 │ ◇</span></span><strong>{name}{(s.design||'pink-capsule')===id?' ✓':''}</strong><small>{desc}</small></button>)}</div><p className="small muted">바와 팝업에 즉시 적용되고 다음 실행에도 유지돼요. 메인 앱 테마와 독립적으로 선택해요.</p><p className="small muted">위치: 게임 모니터 맨 아래 · 한 줄 56px · 게임 종료/최소화/다른 앱 전환 시 숨김<br/>Ctrl+선택 키로 표시/숨김 · 항목 클릭 시 작은 팝업. 자동 표시는 입력 통과 상태예요. 독점 전체화면은 표시가 제한될 수 있어요. 테두리 없는 창 모드를 권장해요. G 단독은 가로채지 않으며, 게임별 단축키 간섭은 실제 게임에서 확인이 필요해요.</p><div className="account-actions"><button className="button secondary" onClick={()=>send('overlay.preview')}>Gaming Bar 미리보기</button><button className="button secondary" onClick={()=>send('overlay.hide')}>숨기기</button></div></section>}
