import React from 'react';
import {Target,Shield,Play,ArrowUpRight,Clock,User,TrendingUp,Swords,Trees,Wand2,Crosshair,Heart,Eye,Orbit} from 'lucide-react';
import {send,duration} from './bridge';
import './riot.css';
import {GameHero} from './GameTheme';
import {LeagueAccount,LeagueMatches} from './LeagueAccount';
import {ValorantAccount} from './ValorantAccount';

const config={valorant:{label:'VALORANT',tag:'PRECISION / TEAMWORK',character:'Agent',points:'RR',description:'한 라운드의 집중, 다음 승리를 향해.',Icon:Target},league:{label:'League of Legends',tag:'STRATEGY / TEAMPLAY',character:'Champion',points:'LP',description:'협곡에서 시작되는, 우리만의 한 판.',Icon:Shield}};
const clock=s=>{const n=Math.max(0,Math.floor(s||0));return [Math.floor(n/3600),Math.floor(n/60)%60,n%60].map(v=>String(v).padStart(2,'0')).join(':');};
const status=g=>g.running?'플레이 중':g.clientState==='gameClient'?'LoL Client 실행 중 · 경기 대기':g.clientState==='riotClient'?'Riot Client 실행 중 · 게임 대기':'실행되지 않음';
function State({game}){return <span className={'badge '+(game.running?'positive':'')}><span className={'dot '+(game.running?'':'idle')}/>{status(game)}</span>}
function Launch({game}){return <button className="button" disabled={game.running} onClick={()=>send('launch',{game:game.id})}><Play size={16}/>{game.running?'플레이 중':'게임 / 런처 실행'}</button>}
export function RiotHomeCard({game,navigate,profile}){const c=config[game.id];return <section className={'card game-card riot-home '+game.id+(game.running?' riot-active':'')}><div className="game-top"><div className="game-symbol"><c.Icon/></div><State game={game}/></div><span className="eyebrow">{c.tag}</span><h2>{game.name}</h2><p>{c.description}</p><div className="riot-summary"><Shield size={18}/><span>{game.id==='league'?(profile?.data?profile.data.riotId+' · '+(profile.data.ranks?.[0]?.tier||'Unranked'):'Riot ID 연결 후 랭크 확인'):(profile?.riotId?profile.riotId+' · '+(profile.rank||'조회 대기'):'Riot ID 연결 후 랭크 확인')}</span></div><div className="between playtime"><Clock size={15}/><span>오늘 플레이</span><strong>{duration(game.today)}</strong></div><div className="card-actions"><Launch game={game}/><button className="button secondary" onClick={()=>navigate(game.id)}><ArrowUpRight size={18}/>상세</button></div></section>}
function Stat({label,value}){return <div className="riot-stat"><span>{label}</span><strong>{value??'—'}</strong></div>}
function MatchList({matches,c}){return <section className="card riot-matches"><span className="eyebrow">MATCH HISTORY</span><h2>최근 경쟁전</h2>{matches?.length?matches.map(m=><article className="riot-match" key={m.id}><strong>{m.result}</strong><div>{m.imageUrl&&<img src={m.imageUrl} alt=""/>}<span>{m.characterName}</span></div><span>{[m.kills,m.deaths,m.assists].map(v=>v??'—').join(' / ')} K/D/A</span>{m.cs!=null&&<span>{m.cs} CS</span>}<strong>{m.pointsChange==null?'—':`${m.pointsChange>0?'+':''}${m.pointsChange}`} {c.points}</strong><span>{m.map} {m.score}</span><time>{new Date(m.playedAt).toLocaleString('ko-KR')}</time></article>):<div className="riot-empty"><Clock size={26}/><h3>아직 연결된 경기 기록이 없어요</h3><p>계정 연동 후 승패, {c.character}, K/D/A{c.points==='LP'?', CS':''} 기록을 이곳에서 확인할 수 있어요.</p><span className="small muted">실제 데이터 연결 전에는 예시 전적을 표시하지 않아요.</span></div>}</section>}
export function RiotPage({id,data}){const c=config[id],game=data.games.find(g=>g.id===id)||{id,name:c.label},view=data.riot?.[id],profile=id==='league'?view?.data:view;return <div className={'riot-page riot-world-body '+id}>
 <GameHero id={id} settings={data.settings} game={game}/>
 <section className="session-strip"><Clock/><div><span>이번 실행 · 앱 감지 기준</span><strong>{game.running?clock(game.session):'실행되지 않음'}</strong></div><div><span>오늘 플레이</span><strong>{id==='league'?clock(game.today):duration(game.today)}</strong></div><div><span>최근 7일</span><strong>{duration(game.week)}</strong></div><p>냥게이밍이 켜져 있는 동안 게임 프로세스가 실행된 시간만 기록해요. {id==='league'?'LoL은 실제 경기 프로세스 기준이에요.':'게임 내 메뉴에 머무른 시간도 포함돼요.'}</p></section>
 <div className="riot-columns">{id==='league'?<LeagueAccount view={view}/>:<ValorantAccount profile={profile}/>}
 <section className="card"><span className="eyebrow">YOUR {c.character.toUpperCase()}</span><h2>{id==='league'?'나의 챔피언':'나의 요원'}</h2>{id==='valorant'&&profile?.characters?.length>0&&<p className="small muted">Valking 최근 요원 통계 · 아래 경쟁전 목록과 집계 범위가 달라요.</p>}{id==='league'&&profile&&<p className="small muted">최근 {profile.matches?.length||0}경기 기준 · 모든 공개 큐{profile.assetMessage&&<><br/>{profile.assetMessage}</>}</p>}{profile?.characters?.length?profile.characters.map(x=><div className="riot-character" key={x.name}>{x.imageUrl&&<img src={x.imageUrl} alt={x.name}/>}<h3>{x.name}</h3><p>{x.games??'—'} 경기 · 승률 {x.winRate??'—'}%</p>{id==='league'&&<p className="small muted">{x.wins}승 {x.losses}패 · 평균 {x.kills} / {x.deaths} / {x.assists} K/D/A · {x.cs} CS</p>}</div>):<div className="riot-empty"><c.Icon size={40}/><h3>{id==='league'?'챔피언':'요원'} 기록을 기다리고 있어요</h3><p>계정 연동 후 최근 플레이 기록을 확인할 수 있어요.</p></div>}<div className="riot-roles" aria-label={id==='league'?'챔피언 포지션':'요원 역할'}>{(id==='league'?[['탑',Swords],['정글',Trees],['미드',Wand2],['바텀',Crosshair],['서포터',Heart]]:[['타격대',Crosshair],['척후대',Eye],['전략가',Orbit],['감시자',Shield]]).map(([label,Icon])=><div className="riot-role" key={label}><Icon/><span>{label}</span></div>)}</div></section></div>
 {id==='league'?<LeagueMatches data={profile}/>:<MatchList matches={profile?.matches} c={c}/>} <div className="privacy-note"><TrendingUp size={18}/><p>게임 실행 감지와 플레이시간은 현재 사용 가능해요.<br/>{id==='league'?(profile?.source==='iplol'?'League 기록은 아이피롤에서 제공받으며 사이트 갱신 상태에 따라 달라질 수 있어요.':'League 기록은 Riot 공식 API와 Data Dragon에서 제공받아요.'):'발로란트 기록은 Valking 공개 전적에서 제공받으며, 사이트 갱신 상태에 따라 달라질 수 있어요.'}</p></div>
 </div>}
