import React from 'react';
import {Bell,BellOff,Users,Clock3} from 'lucide-react';
import {send,duration} from './bridge';
import './social.css';
const names={genshin:'원신',eternal:'이터널 리턴',league:'League of Legends',valorant:'VALORANT'};
const states={none:'설정 안 함',looking:'같이 할 사람 구함',playing:'게임 중',away:'자리비움'};
const defaults={loginNotifications:true,partyState:'none',partyGame:'',mutedFriends:[]};
const options=view=>({...defaults,...view.social?.options});
const change=(view,patch)=>send('friends.social',{...options(view),...patch});
const time=n=>n>0&&n<60?'1분 미만':duration(n);
export function PartySettings({view}){const o=options(view);return <section className="card social-party"><span className="eyebrow">PLAY TOGETHER</span><h2><Users size={22}/> 나의 파티 상태</h2><div className="party-controls"><label>상태<select value={o.partyState} disabled={!view.me} onChange={e=>change(view,{partyState:e.target.value})}>{Object.entries(states).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>함께할 게임<select value={o.partyGame} disabled={!view.me||!view.options?.shareGame||['none','away'].includes(o.partyState)} onChange={e=>change(view,{partyGame:e.target.value})}><option value="">게임 미지정</option>{Object.entries(names).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label></div><p className="small muted" role="status">{view.social?.message||'친구 프로필을 만든 뒤 파티 상태를 설정해 주세요.'}{view.options?.shareGame===false?' 게임 활동 공유가 꺼져 있어 게임 이름은 숨겨져요.':''}</p></section>}
export function PartyBadge({view,friend}){if(view.stale||!view.social?.connected||friend.status==='offline')return null;const p=view.social.parties?.find(p=>p.id===friend.id);return p&&p.state!=='none'?<span className={'party-badge party-'+p.state}>{states[p.state]||''}{p.gameId&&names[p.gameId]?` · ${names[p.gameId]}`:''}</span>:null;}
export function FriendNotificationButton({view,friend}){const o=options(view),enabled=!o.mutedFriends.includes(friend.id);return <button className="button secondary friend-alert-button" aria-label={`${friend.nickname} 접속 알림`} title={enabled?'이 친구의 접속 알림 끄기':'이 친구의 접속 알림 켜기'} aria-pressed={enabled} disabled={!o.loginNotifications} onClick={()=>change(view,{friend:friend.id,muted:enabled})}>{enabled?<Bell size={16}/>:<BellOff size={16}/>}</button>}
export function ArrivalSettings({view}){return <label className="friend-toggle"><span>친구 접속 알림<small className="social-help">이미 접속한 친구와 재연결에는 알리지 않아요. 친구별 벨 버튼으로 끌 수 있어요.</small></span><input type="checkbox" checked={options(view).loginNotifications} onChange={e=>change(view,{loginNotifications:e.target.checked})}/></label>}
export function WeeklySummary({view={}}){const s=view.social||{},w=s.weekly;const diff=w?(w.seconds||0)-(w.previousSeconds||0):0;return <section className="card weekly-summary"><span className="eyebrow">MY WEEK IN GAMES</span><h2><Clock3 size={22}/> 이번 주 플레이 요약</h2>{w?<><p className="small muted">{w.weekStart} 월요일부터 · 지난주({w.previousStart}부터 7일) 전체와 비교</p><div className="weekly-totals"><div><span>이번 주 현재까지</span><strong>{time(w.seconds)}</strong></div><div><span>지난주 전체</span><strong>{time(w.previousSeconds)}</strong></div><div><span>지난주 대비</span><strong>{diff===0?'변화 없음':`${time(Math.abs(diff))} ${diff>0?'증가':'감소'}`}</strong></div></div><h3>이번 주 많이 한 게임</h3>{w.games?.length?<ol className="weekly-games">{w.games.map(g=><li key={g.gameId}><span>{names[g.gameId]||g.gameId}</span><strong>{time(g.seconds)}</strong></li>)}</ol>:<p className="muted">이번 주 완료된 게임 기록이 아직 없어요.</p>}</>:<p className="muted">{view.me?'주간 요약을 확인하고 있어요.':'친구 프로필을 만들면 내 주간 요약을 볼 수 있어요.'}</p>}<p className="small muted" role="status">{s.weeklyMessage}{s.weeklyStale&&w?' · 마지막으로 조회한 기록입니다.':''}</p><p className="small muted">진행 중인 게임은 종료 후 반영돼요. 요약은 최대 5분 간격으로 갱신됩니다.</p></section>}
